### ISSUE TITLE
Create <Colors> component to replace <!-- colors --> in /design/colors.md

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10146]
polaris.shopify.com/design/colors is broken in the move to mdx because the way we are creating the color palette on that page does not play nice with mdx. 

Currently the logic that replaces the  code is in markdown.mjs

![Image](https://github.com/Shopify/polaris/assets/4642404/2827b7c4-c797-4580-92ca-cfe32e3b2edd)

Right now the site will error out because mdx does not support html comments.

![Image](https://github.com/Shopify/polaris/assets/4642404/48a4eaf9-590e-4860-a3c3-de9cea704e94)

**Comment by yurm04** [comment]
Before fixing this page @tjonx @zecarlostorre do you have an idea of how/if a color palette will fit into the new design guidance? I'm going to move this into `Needs Design` in case you have thoughts about changing it from what exists today. If there are no changes, i'll just migrate what we have to be mdx-compliant

**Comment by tjonx** [comment]
I was thinking of making an interactive palette for this section instead of just throwing a bunch of swatches with little context.
The global color palette is built with HSLuv and the documentation speaks to this. If we could have an interactive palette that shows the contrast ratio between 2 colors, that would be pretty useful to designers!

Figma: https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=315-30700&mode=design&t=RlBSml6lqQssYjnR-4

There's also a great article that shows how to do this in js: https://dev.to/alvaromontoro/building-your-own-color-contrast-checker-4j7o
