### ISSUE TITLE
[TooltipOverlay] Tooltip arrow is off position for one character

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10163]
This bug happens both with the se23 flag on and off

![Image](https://github.com/Shopify/polaris/assets/20652326/74a4a7f3-b699-46f4-9c98-7a710f43ab17)
![Image](https://github.com/Shopify/polaris/assets/20652326/1f82ee41-8672-4b76-aa74-11dccb2bb29e)

**Comment by yurm04** [comment]
We have a proposed solution in this PR https://github.com/Shopify/polaris/pull/11304 with screenshots of the before and after

We're setting a `min-width` of at least `4ch` so that the tooltip tail is not offset, but with a `4ch` min on a one character tooltip the one character will not be center aligned. This can be mitigated by the implementer wrapping the character in a div that sets `text-align: center`. 

The other option to center align the 1 character would be to set it ourselves in `TooltipOverlay`, but we would need to check and count the `content` of the tooltip, which feels a bit hacky logic but doable.

Any thoughts on this approach?



![Image](https://github.com/Shopify/polaris/assets/4642404/e5a614af-a351-49ed-a858-7ba8ab095a06)

**Comment by heyjoethomas** [comment]
Seems like this is an extreme edge case no matter what. A single character tooltip is totally useless anyway. So i'm fine with this.

**Comment by lgriffee** [comment]
Re-opening this issue until 

- https://github.com/Shopify/polaris/pull/11351 

is shipped to prod.
