### ISSUE TITLE
[Skeleton tabs] Update SkeletonTabs to reflect Tabs component

### ISSUE THREAD

**Issue by martinamarien** [Shopify/polaris-react-archive#10279]
### Problem
Polaris has a new [Tabs component](https://polaris.shopify.com/components/navigation/tabs) that replaces the [LegacyTabs component](https://polaris.shopify.com/components/navigation/legacy-tabs).

Currently, the [SkeletonTabs](https://polaris.shopify.com/components/feedback-indicators/skeleton-tabs) component still reflects the `LegacyTabs` component, forcing devs to create custom skeleton states on page load.

### Request 
To create a `SkeletonTabs` component that reflects the new Tabs component.

**Comment by yurm04** [comment]
Is there a new design associated with the Skeleton tabs?

**Comment by heyjoethomas** [comment]
@yurm04 Here is the design. Let me know if you have questions. https://www.figma.com/file/jLLkmo9r28hiqPvf4s90E4/branch/12F2Pi4uZ3PJQgTPjbHgPh/Polaris-Gen-3-Components?type=design&node-id=113973-39695&mode=design&t=reR54kMq05COztXb-11

**Comment by yurm04** [comment]
@heyjoethomas the current skeleton tabs have a small line at the bottom indicating the "current tab" (fake). Do we want to keep this?

<img width="283" alt="Screenshot 2024-01-05 at 12 20 05 PM" src="https://github.com/Shopify/polaris/assets/4642404/74d55616-f57b-46c6-bdff-f8ecc8e31f7d">

**Comment by yurm04** [comment]
@heyjoethomas when I update the padding around the tabs to match the Figma design the spacing is a lot tighter. Want to make sure this is intentional or if i should leave the top/bottom spacing as is and update only the right/left to match the figma.

<img width="229" alt="Screenshot 2024-01-05 at 12 39 08 PM" src="https://github.com/Shopify/polaris/assets/4642404/13bb128a-dab0-4484-8324-4432e6fd4e2e">

<img width="214" alt="Screenshot 2024-01-05 at 12 39 17 PM" src="https://github.com/Shopify/polaris/assets/4642404/762e4888-1a4c-4d8e-8cd6-28757140a2d8">

**Comment by lgriffee** [comment]
@heyjoethomas Should have a PR up for this today!
