### ISSUE TITLE
Moving component descriptions into `<Lede>` removes descriptions from `/components` page

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10364]
Removing description from the component page metadata and using it directly in the `<Lede>`, we lose all the information on the `/components` root page. Imo it makes the page a bit inconsistent with the other ones that include descriptions on the grid (i.e., patterns page). This is not the intended outcome and we will need to re-add the descriptions to the `/components` url

_Originally posted by @laurkim in https://github.com/Shopify/polaris/pull/10214#pullrequestreview-1616009108_

Issue
<img width="2032" alt="Screenshot 2023-09-07 at 2 51 06 PM" src="https://user-images.githubusercontent.com/4642404/266426789-da66e97c-594e-4ba7-bd5a-8e1c177b192d.png">

Original
<img width="2032" alt="Screenshot 2023-09-07 at 2 51 27 PM" src="https://user-images.githubusercontent.com/4642404/266426874-a35d40a8-2e79-46bf-8884-c016b90026b3.png">

**Comment by jesstelford** [comment]
I'm wondering if the long descriptions are the correct ones to show on the preview cards?

I've seen this in other places too; the long description doesn't show enough information before it's truncated, effectively making it useless 🤔  There's also the issue with markdown; the description can contain arbitrary markdown which is why it's been pushed into the content instead of the frontmatter, but I think it makese more sense to have plain text in the preview cards.

We've already got a mechanism/types for setting a specific `seoDescription` in the frontmatter which will override the `description` frontmatter or `firstParagraph` auto generated value. Should we perhaps add a `shortDescription` option also?

That'd be a lot of work to write a short description for every component, so in the mean time I'll look at leveraging the `seoDescription` to get it showing on the preview cards.
