### ISSUE TITLE
`/patterns/*` live examples error

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10400]
Two issues with the pattern live examples on a patterns pages:

1. When you first load the website locally using `yarn run dev` and navigate to `/patterns/app-settings-layout` there is an error loaded in the example. This only happens of the first load and then by navigating to `/patterns` => `/patterns/app-settings-layout`
![Image](https://github.com/Shopify/polaris/assets/4642404/0f41e816-5ab0-4445-bbc9-e59155d1c1b8)

2. The patterns example `Show code` button does not work when clicked

https://github.com/Shopify/polaris/assets/4642404/baaafc73-ec7b-4b01-89c7-fb7981dd80f3

**Comment by gwyneplaine** [comment]
@yurm04  first issue only happens locally due to us having two servers:
1) next server running the docs site 
2) a webpack dev server running the playroom instance 

This won't happen in prod or staging, as they will all be prebuilt artefacts. Worthwhile noting that this was happening before the uplift docs updates. That said happy to look into it a bit more if its something you feel strongly about but it may be significant effort 👍 

Looking into the second issue now 👍

**Comment by jesstelford** [comment]
To add some more detail to issue #1; The local webpack server @gwyneplaine mentioned _takes longer to boot up_, which is why you're only seeing it when you first load the page - the local Playroom server is still starting. If you watch the terminal output, you'll see it starts about 5-10s after Next does (something like `Listening on port 9000`), then the embedded playroom examples will work without issue 👍
