### ISSUE TITLE
Create <Bleed> component that can be used in a .md file

### ISSUE THREAD

**Issue by gwyneplaine** [Shopify/polaris-react-archive#10546]
Card compositions involving full width images / assets in #10150 such as the [MediaCard](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=50%3A4050&mode=design&t=kQj4os2WflWtJs5B-1)  require negative margin. 
We should have a lightweight Bleed component for use in these compositions.

**Comment by gwyneplaine** [comment]
Not sure if we need this, dependent on what our decision is around using layout primitives from `@shopify/polaris` in the docs site

**Comment by yurm04** [comment]
@gwyneplaine You can go ahead and use the `Bleed` component! Layout components should be fine to use in the site since. Since we're adding the design language to the site as well, we can start to pull in components where it makes sense (though not all polaris-react components will work in the site without `AppProvider`)

**Comment by gwyneplaine** [comment]
Yay, we can use layout components from polaris, closing this issue 🎉
