### ISSUE TITLE
Font used in design is not the as the latest version from apple

### ISSUE THREAD

**Issue by senadir** [Shopify/polaris-react-archive#106]
# Issue summary

sketch file using a font version that seems out of sync with the latest apple version

![table of contents](https://user-images.githubusercontent.com/6165348/27512522-16bfda22-593b-11e7-907e-de574f0c13c0.png)

I've download the latest version but still got the error every time I open the file

**Comment by ry5n** [comment]
I’m able to reproduce this using the latest version of SF Pro from Apple and we’ll make some updated to account for the changes in San Francisco.

**Comment by astrism** [comment]
Just wanted add my screenshots since I have a similar issue with different results. The tester screen looks incorrect but the screen posted by @senadir looks ok using the latest SF Pro download.

<img width="256" alt="screen shot 2017-07-08 at 11 13 28 am" src="https://user-images.githubusercontent.com/48418/27988099-c728d538-63ce-11e7-8a19-12197a510a88.png">
<img width="647" alt="screen shot 2017-07-08 at 11 11 40 am" src="https://user-images.githubusercontent.com/48418/27988098-c7257492-63ce-11e7-814e-7d57aa52048b.png">

**Comment by ry5n** [comment]
Thanks for weighing in. We’re in the process of updating the Sketch files to use SF Pro. That version will be available with the next release of Polaris.

In the meantime, in Sketch 44+, you can try “File > Replace missing fonts…” and replac the missing SF UI with SF Pro. This may resolve some of the wrapping issues.

![screen shot 2017-07-08 at 1 48 19 pm](https://user-images.githubusercontent.com/804014/27989019-c9b79ae4-63e4-11e7-878f-8ad30bfced2b.png)

**Comment by ry5n** [comment]
This has been addressed with the revised UI kit in Polaris 2.0. Let me know if you still run into any issues with the fonts. Thanks!
