### ISSUE TITLE
[IndexFiltering] Ability to present the search filter bar by default when tabs/saved views are not present.

### ISSUE THREAD

**Issue by zaquille-oneil** [Shopify/polaris-react-archive#10728]
## IndexFiltering

Short intro description (try and keep to two sentences):

> When no tabs are present in the IndexFiltering component, we want the ability to expose the Search bar without having to click the CTA for search+filter

Not all index tables will have a need for tabs or saved views. Today, there is "dead" whitespace prior to clicking on the search+filter CTA. Making this change will allow merchants to have a better IndexFiltering UI.

Example:

<img width="1106" alt="image" src="https://github.com/Shopify/polaris/assets/4310197/96916e27-0ffc-40e2-a6d3-3b0a19dd80fe">
<img width="1105" alt="image" src="https://github.com/Shopify/polaris/assets/4310197/4f241e32-ead1-4612-b3e6-5dcbad5052c7">

## Required components

TBD

Example for default callout card:

TBD

Example for callout card with secondary action:

TBD

## Props

List props and type declarations: TBD

> - **propName** (required or optional): `type` defaults to `value` – description of the prop

Example:

> - **showFoo** (required): `boolean` – Show or hide foo
> - **showBar** (optional): `boolean` defaults to `false` – Show or hide bar
> - **items** (optional): `ItemDescriptor[]` – Collection of items
> - **onClick** (optional): `() => void` – Callback when clicked

### Subtype name

This section is only used if any prop types use a structural subtype, called interfaces in TypeScript. List props and type declarations of the subtype like above:

> - **propName** (required or optional): `type` defaults to `value` – description of the prop

Example:

> ### ItemDescriptor
>
> - **accessibilityLabel** (optional): `string` – Visually hidden text for screen readers
> - **content** (optional): `string` – Content the action displays
> - **disabled** (optional): `string` – Should the action be disabled

## Best practices

The {x} component should:

- This is where you should include design best practices and UX guidelines.

Example:

> The select component should:
>
> - Be used for lists of four or more items
> - List items within the menu alphabetically or some other logical order so mer_chants can easily find the selection they need
> - ...

## Content guidelines

{x} should:

- Content guideline here

| Do example | Don’t example |
| ---------- | ------------- |
| Do this    | Don’t do this |

## Subcomponent name

This section is only used for components with subcomponents. Include a short intro description of the subcomponent purpose and how it relates to the main component.

Example:

> The content of a resource list consists of resource list items. Each item summarizes an individual resource and should link to its show page.
> Because the content of items depends on the type of resource and merchant tasks, resource list items are flexible.

### Subcomponent examples

Description of example (clearly differentiate examples from each other). Use an image if applicable:

> **Subcomponent example name**
>
> Use {component name} to let merchants {x}.
>
> ![Aww kitty](https://placeimg.com/300/100/arch/grayscale)

Example:

> ### Item examples
>
> **Simple resource list item**
>
> A basic resource list item with its details filled in at the point of use.

## Related components

- To {describe how the other component works}, [use the {x} component]

Example:

> - To {learn how to embed a link in a piece of text}, use the {link} component

**Comment by amandaspilchen** [comment]
The specific scenario we need this for is when catalogs (B2B today, but POS soon, and many other catalogs in the future) have a publication deleted. This would result in merchants only being able to manage the prices of products in a catalog, and not the products that get included. 

For anyone viewing this ticket in the future, you can refer to this scenario in our figma build file for [POS catalogs](https://www.figma.com/file/TOMo2aHZz5stBikt23oa27/(Retail)-Point-of-Sale-Catalogs?type=design&node-id=2380%3A318252&mode=design&t=CGwoHDqJNyJJl5uT-1)

It's worth calling out:
- Our variant view for this editor does not control publishing today (because we do not have variant level publishing in Shopify) so there's already variance for us in these two views (products view of the table needs tabs, variant view doesn't). 
- We noticed that the Customers index needed a custom view because it also doesn't have tabs today. We originally wanted our view for catalogs (when publications are deleted/non-existant) to be like this. After looking, we realized that this was custom and not something we could do with the catalogs editor today. Their needs are also a bit different, since we require filters and they do not have any today. So having an entry point for filters while still leaving search expose would be a helpful.
