### ISSUE TITLE
[polaris.shopify.com] Inter needs to be loaded as a variable weight font

### ISSUE THREAD

**Issue by tjonx** [Shopify/polaris-react-archive#10894]
## Issue summary / Current behavior

On staging, regular and semibold fonts are bolder than they should be. This looks like the font we load (Inter) is being loaded per weight and not as a variable weight font. 
`<style data-href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;display=swap">`

Our Regular font weight was changed from `400` to `450`, but it gets rounded up to `500` because we're not loading the variable weight version of Inter.

https://github.com/Shopify/polaris/assets/67433661/4e86774d-7fce-47cf-acbe-91e7f255b148

Same thing happens (less noticeably because it's used less) with Semibold, which went from `600` to `650`, but is getting rounded up to `700`.

## Expected behavior

The font needs to be loaded as a variable weight font:

`<style data-href="https://fonts.googleapis.com/css2?family=Inter:wght@400..700&amp;display=swap">`

or load the new weights for regular and semibold instead: 
`<style data-href="https://fonts.googleapis.com/css2?family=Inter:wght@450;500;650;700&amp;display=swap">`

**Comment by bakura10** [comment]
Hi!

I am not sure if the root cause is Polaris or Chrome, but on Chrome Canary, I am experiencing a much bolder style for buttons, headings...

Chrome stable:

<img width="167" alt="image" src="https://github.com/Shopify/polaris/assets/1198915/dd40deac-66ed-4fd0-89bc-7f2ee2a8f0a0">

Chrome canary:

<img width="192" alt="image" src="https://github.com/Shopify/polaris/assets/1198915/6b541ec1-2734-4081-81c9-e31051d9e04e">
