### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by dhvanibvi** [Shopify/polaris-react-archive#11068]
"disableSpecificDates" is not working with a single date picker and date range picker both

```
  const disableSpecificDates = [
    new Date('Mon Feb 12 2018 00:00:00 GMT-0500 (EST)'),
    new Date('Sat Feb 10 2018 00:00:00 GMT-0500 (EST)'),
    new Date('Wed Feb 21 2018 00:00:00 GMT-0500 (EST)'),
  ];
  <DatePicker
                  month={month}
                  year={year}
                  onChange={setSelectedDates}
                  onMonthChange={handleMonthChange}
                  selected={selectedDates}
                  disableDatesBefore={new Date('Sat Feb 03 2018 00:00:00 GMT-0500 (EST)')}
                  disableDatesAfter={new Date('Sun Feb 25 2018 00:00:00 GMT-0500 (EST)')}
                  disableSpecificDates={disableSpecificDates}
                />
```

**Comment by fabregas4** [comment]
This should be re-opened. Prop who's intended functionality does not work at all, even on Shopify's official example at:
https://polaris.shopify.com/components/selection-and-input/date-picker?example=date-picker-with-specific-disabled-dates

**Comment by fabregas4** [comment]
Turns out you need the time to match exactly with local time. This is why the example in Polaris docs doesn't work. For most people anyway, it probably works for people in the timezone specified in the disabledSpecificDates example values.

If you specify dates in this way, it should work:

`new Date('Fri May 23 2025')`

This should work too:

`new Date(2025, 4, 23) // where 4 = May`

This won't work:

`new Date('2025-05-23')`

as this format gets converted to midnight UTC, not local time.
