### ISSUE TITLE
[Modal]: When prop `size="fullScreen"`, there's a funky UX BUG 🐛 

### ISSUE THREAD

**Issue by ginabak** [Shopify/polaris-react-archive#11185]
There's a really funky bug 🐛 when the **[prop `size` on Modal](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Modal/Modal.tsx#L47)** is `"fullScreen"`. 

See video:

https://github.com/Shopify/polaris/assets/43223543/075337d9-c30a-4a5e-885e-111687c012a7

## Steps to reproduce the problem

1. Go to any component that is consuming the Modal
2. Make the screen smaller
3. Notice how the footer is strangely large and consumes most of the screen 🤔 😢

**Comment by yurm04** [comment]
Want to make sure I understand the expected behavior:

Should the main modal content always take up all available space and the footer always be anchored to the bottom? Here's a video demonstrating what I'm describing:

https://github.com/Shopify/polaris/assets/4642404/9cdc6a83-700f-488c-9c7a-89f389b0e31e

**Comment by yurm04** [comment]
☝ Maybe some UXers can weigh in on this question as well @Shopify/polaris-ux

**Comment by heyjoethomas** [comment]
> ☝ Maybe some UXers can weigh in on this question as well [@Shopify/polaris-ux](https://github.com/orgs/Shopify/teams/polaris-ux)

I don't think so. Doing this puts the action really far away from the content. I'm also not sure this is typical behavior across all modals. Here is an example of what I see when looking at a modal on the Order Detail page

![Image](https://github.com/Shopify/polaris/assets/5749440/78decbb9-b607-408b-8da0-36b447d74aa9)

**Comment by xtaraim** [comment]
testing done here

**Comment by chloerice** [comment]
Fullscreen is a mobile-only variant contributed for things like the `ProductResourcePicker` in Gina's screenrecording, because otherwise dynamic content like long, filterable lists cause the modal height to constantly change as you search. The modal footer is supposed to maintain its fixed height and position regardless of screen size, I'm not sure when this bug slipped in, maybe when we refactored it to use the layout components?

**Comment by yurm04** [comment]
@chloerice It looks like this was introduced when we [refactored to layout components](https://github.com/Shopify/polaris/commit/7ffd87f7d5e975cabb1b2e0d303295ae669cbcea#diff-6086869ca738e8eb3275594e423d8d08b91da961a8d399b6d5c5b70965f21f1eL9) and the previous solution was to use `flex-grow`. I'm going to bring that back since I don't  _think_ there's an equivalent with our layout components atm (but please correct me if i'm wrong)

[PR with proposed solution here](https://github.com/Shopify/polaris/pull/11354)

**Comment by lgriffee** [comment]
Reopening until 

- https://github.com/Shopify/polaris/pull/11428

ships

**Comment by lgriffee** [comment]
https://github.com/Shopify/polaris/pull/11354 was reverted due to regressions found in prod. 

- https://github.com/Shopify/polaris/pull/11436
- https://github.com/Shopify/web/pull/114385

**Comment by lgriffee** [comment]
Closing with the release of:
- https://github.com/Shopify/polaris/pull/11454
-  https://github.com/Shopify/web/pull/115164
