### ISSUE TITLE
Button with external=true not working

### ISSUE THREAD

**Issue by ComicDansMS** [Shopify/polaris-react-archive#11307]
## Issue summary

The `external` prop on the Button component is not behaving correctly. If I do the documented way of passing a boolean `external={true}`, TypeScript is happy but the browser gives the following warning:

```
chunk-H5ZE7JVG.js:521 Warning: Received `true` for a non-boolean attribute `external`.
If you want to write it to the DOM, pass a string instead: external="true" or external={value.toString()}.
```

If I change it to a string of `"true"`, TypeScript complains but the browser appears happy.

And to finish, the app crashes when you click the button (with either way of defining the external prop). The app displays the message of "_admin.shopify.com refused to connect._". Links with a normal HTML anchor element open ok with the target attribute set to "_blank".

## Steps to reproduce the problem

Spin up a new remix app template and use the button as per the following:
```
<Button
  variant="primary"
  url={linkUrl}
  external={true}
  icon={ExternalMinor}
>
  Open Link
</Button>
```

For what it's worth, my lock file shows polaris version: `version: 12.2.0(react-dom@18.2.0)(react@18.2.0)`

**Comment by xtaraim** [comment]
testifggf fdfdjnk

**Comment by sam-b-rose** [comment]
I don't see anything unusual with the `BaseButtonProps` which is where `external?: boolean` is defined. 🤔 

Do either of the follow patterns resolve the error from both TS and React?

```jsx
<Button external />

// or

const isExternal = true;

<Button external={isExternal}
```

**Comment by vincaslt** [comment]
This is an issue when using in Remix. It seems like then it uses useLink to get the framework's Link component to use, and that's where it breaks. The types are misleading in that case because Remix doesn't have "external" prop afaik.

The place I get when debugging is somewhere here: https://github.com/remix-run/react-router/blob/94f7fb7b3a3d2ef266f1d83293c5ab50c1963132/packages/react-router-dom/index.tsx#L957-L971
