### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by ozkanoz** [Shopify/polaris-react-archive#11378]
Hi there, when we use the index table (https://polaris.shopify.com/components/tables/index-table?example=index-table-without-checkboxes) we cannot swipe right on mobile devices, and the complete data in the table is not shown.  Can you please help us? What shall we do? 

Thanks in advance! 
Ozkan

**Comment by kyledurand** [comment]
Hi @ozkanoz I think you're asking about side scrolling your content in the index table on small screens. The IndexTable doesn't scroll horizontally on small screens when the `condensed` prop is set to true because critical information could be hidden off screen. We recommend either using css or different markup to stack your content on small screens, according to where you set your condensed breakpoint. 

We have a [small screen example in storybook](https://storybook.polaris.shopify.com/?path=/story/all-components-indextable--small-screen).

Alternatively, if you really need your content to scroll on small screens you can remove the `condensed` prop you have set on your IndexTable implementation

https://github.com/Shopify/polaris/assets/6844391/11b0b1bc-0c3f-46d0-a73c-4b8d1658b263
