### ISSUE TITLE
[Button] Update micro icon only button padding

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#11448]
Micro iconOnly button padding should be 4px not 8px

**Comment by yurm04** [comment]
@sarahill is iconOnly a new prop? Or is it just a button that only has an icon (no text)?

Was there a proposed solution for how to detect that a micro icon is being passed to the button? I don't think we've changed the button styling based on Icon size before. Is it a new button variant? do we expect to auto-detect it? do we add a `padding` prop to button? Just asking questions in case this was discussed when this issue was first opened

**Comment by bernardojoaogarcia** [comment]
I thought the Micro button IconOnly padding was 2px? Is this already anticipating a micro icon migration?

**Comment by sarahill** [comment]
I just remember the padding was disproportional but it looks even now. This might be another one that got fixed somewhere else. It looks like we can close this issue and/or follow up with the micro icon migration with any changes needed there.
