### ISSUE TITLE
Drag-and-drop row support / manual sort for index tables

### ISSUE THREAD

**Issue by rahfyehl** [Shopify/polaris-react-archive#11699]
### Summary

Adding support for a manual sort / drag-and-drop re-order on index tables, similar to other platforms like Notion, Gmail, and Fellow. 
![image](https://github.com/Shopify/polaris/assets/34408700/f80065f2-56b2-47b6-af3c-2bac99346b1e)

### Rationale

On a current project for the 1P app Shopify Search & Discovery, we are working to add custom value sorting to Filters where merchants can re-order their filter values. We use the `IndexTable` for the Values card in the filter details page, and in order to align with other areas of Admin and familiar patterns on other platforms we want to introduce drag-and-drop re-order. However, this is not natively supported in the component with the `drag-handle` icon being second-class to the `checkbox`. 

Adding this functionality natively also has the benefit of added functionality and flexibility to merchants in the `IndexTable` component where the default sorts may not work for the merchant and they would like to order the content a specific way. 

This would also result in informing how other Polaris components could implement drag-and-drop, e.g the `drag-handle` placement, what drop zones look like, how the interaction works, how the interaction animates, etc.

**Comment by chloerice** [comment]
Hey @rahfyehl 👋🏽 This is not something that should be added to `IndexTable`, which is quite a hefty and overly complex component as it is. This would need to be a new drag/sort list component, and is not something I'd recommend adding to the system right now due to pending changes to where Polaris code lives (moving to internal-only), other governance/logisitics changes, and due to drag sort being a rare need (only one instance in admin, manual product sort in /collections). I've spoken to @jas7457 and am pointing him to the code used in the collections section in web to help unblock y'all.
