### ISSUE TITLE
Sketch grid and layout guidance

### ISSUE THREAD

**Issue by micahtaylor** [Shopify/polaris-react-archive#12]
# Issue summary

The Sketch file is a thing of beauty. Thank you for the hard work and inspiration.

Would love to see some more consistency in the spacings.
<img width="355" alt="screen shot 2017-04-21 at 3 21 45 pm" src="https://cloud.githubusercontent.com/assets/671894/25294884/c44216f0-26a6-11e7-942c-3fa3577dd5ac.png">
☝️ is just one example but found a handful of others.

Would also love to see some guidance as to the grids and guides used. At times spacing was a factor of 10px other times they were factors of 8px.

- Polaris version: v1.0.0
- Sketch version: 43.2
- Device: Mac
- Operating System: macOS Sierra

**Comment by jessebc** [comment]
Thanks for catching this @micahtaylor! We'll do our best to get stuff like this fixed up in an upcoming release. 

"Spacing" is on our list of things that we would like to add to the style guide. 

For now, we're defaulting to increments of 4px. Exceptions are made however for internal padding within components in order to have the overall height land on a 4px increment.

There are a couple of items that break this rule (slim buttons come to mind) and we'll either make adjustments to those in the future or document those exceptions in the style guide when we add the spacing section.
