### ISSUE TITLE
Disable pre/next buttons even previousURL/nextURL provided

### ISSUE THREAD

**Issue by donnguyen** [Shopify/polaris-react-archive#141]
Pagination component:

Given that we have `hasNext = false`, I think better to disable Next button anyway even if we have nextURL present. IMO, it makes more sense, what do you guys think?

BTW, on documentation it should be `nextURL` not `nextUrl`.

Cheers

**Comment by donnguyen** [comment]
Any ideas here guys?

**Comment by ry5n** [comment]
Update: we’ve fixed the typo in the documentation, but I’m not totally clear on the feature request.

Currently, `hasNext` toggles the enabled/disabled state of the next button regardless of the presence/absence of `onNext` or `nextUrl`. I realize this issue is from a long while ago, so it’s possible this was changed in the meantime, but the current behavior seems to match what you wanted.

Please definitely re-open the issue if it’s not actually working the way you’d expect.
