### ISSUE TITLE
Why use px instead of em?

### ISSUE THREAD

**Issue by hmaesta** [Shopify/polaris-react-archive#18]
–Not an issue, just a question.–

**On [typography](https://polaris.shopify.com/visuals/typography), why using `px` instead of using `em`?**

It's obvious that as a designer we have more control of everything using `px`, but using `em` or `rem` we put the user first, assuming his preferences and limitations.

A person with visibility limitations can set his default font size as Big on browser settings, but he won't see any difference in a site using `px`.

I am not saying that `px` is bad, ugly and smell, just trying to understand the choice.

**Comment by lemonmade** [comment]
Hey @hmaesta, thanks for making an issue. We actually do use `rem` for all font size measurements — you can see it in the source here: https://github.com/Shopify/polaris/blob/master/src/styles/foundation/typography.scss#L45-L82. We only display it as `px` on the styleguide because there is no way to reliably show measurements in `rem`/ `em`, since it depends on some other, potentially changeable font-size (`html` and the parent element, respectively).
