### ISSUE TITLE
SFUI fonts necessary to Sketch UI kit not included

### ISSUE THREAD

**Issue by adamnel** [Shopify/polaris-react-archive#22]
# Issue summary

After downloading the UI kit, when opening it I'm presented with a missing fonts dialog but am not given the fonts necessary to reconcile the issue.

## Expected behavior

I should be presented ahead of time with font requirements and download locations.

## Actual behavior

I'm presented with an error dialog, and the natural next step is to go looking for the fonts, not dismiss it and open the file anyway, which is the only way to see the link to get the necessary fonts.

**Comment by ry5n** [comment]
Thanks for pointing this out @adamnel. As a rule we wanted to put the how-to info inside the sketch file itself, but in this case it doesn’t work out. Since we can’t distribute the font files themselves (Apple’s license prohibits it) we’ll consider some ways of making the download links more obvious.
