### ISSUE TITLE
Feature Request: send a Shopify.API.replaceState message whenever a new Page is loaded

### ISSUE THREAD

**Issue by mikeyhew** [Shopify/polaris-react-archive#221]
The old Embedded App JS code used to call `ShopifyApp.replaceState` with the current `window.location.pathname` whenever you called `ShopifyApp.Bar.initialize`, with the intuition that if you were updating the bar, the url may have changed. This ended up being really annoying, because it didn't filter out any of the query string parameters (i.e. `shop`, `hmac`, `timestamp`) that Shopify adds to the iframe url, and I ended up creating a workaround, but the overall idea was good: the point was so that the merchant could refresh the page and stay at the same page in the app. Currently, with Polaris, if the user refreshes the page, they will be returned to the app's home page.

Now that we're using Polaris, I created a subclass of the `Page` component that calls `replaceState` whenever it updates the bar, just like the old EASDK code, except that it runs through the query parameters and filters out the `shop`, `hmac`, `timestamp`, `protocol`, and `locale` parameters. Here is the code, available under the [CC0 License](https://creativecommons.org/share-your-work/public-domain/cc0/) (public domain).

```jsx
import {Page as PolarisPage} from '@shopify/polaris'

const FILTER_REGEX = /(^|&)(timestamp|protocol|hmac|shop|locale)=[^&]*/g

const filteredQuery = () => {
  const filtered = window.location.search.slice(1).replace(FILTER_REGEX, '')
  if (filtered.length > 0) {
    return '?' + filtered
  } else {
    return ''
  }
}

export default class Page extends PolarisPage {
  handleEASDKMessaging(...args) {
    const ret = super.handleEASDKMessaging(...args)
    const location = window.location.pathname + filteredQuery()
    this.context.easdk.messenger.send('Shopify.API.replaceState', {location})
    ret
  }
}

```

Would you be interested in adding this behaviour to Polaris? It could be implemented as a config attribute on `Page`, or as a subclass like this example. Or if you don't think people are relying on the current behaviour, you could just integrate this into the current `Page` without any config.

**Comment by tmlayton** [comment]
Hi @mikeyhew, thanks for the code and feedback. We won't be adding this to Polaris, although it is possible we would add this to the Embedded App JS. For more context, we are in the midst of updating and moving the Embedded App JS to its own node package. When that work is complete, Polaris will consume the Embedded App JS package and its components will wrap `ShopifyApp`.

We have already experienced some drift between using `ShopifyApp` and Polaris Embedded App components partly because we are maintaining the API in two places. We intend to close that gap.
