### ISSUE TITLE
IOS Popover CSS Fix

### ISSUE THREAD

**Issue by jason-engage** [Shopify/polaris-react-archive#270]
Popovers not working properly on IOS devices.

display:flex should come before display:-webkit-box in order to fix this issue in the following line:

`.Polaris-Popover__Content{position:relative;display:-webkit-box;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-ms-flex-direction:column;flex-direction:column;border-radius:6px;max-width:40rem;max-height:29.5rem}`

**Comment by lemonmade** [comment]
Hi @jason-engage. We use [autoprefixer](https://github.com/postcss/autoprefixer) for generating our vendor prefixes, so we don't have much control here. However, the correct order is to use the standards-compliant value last in the declaration (here, `display: flex`, so that it takes precedence over the other values.

What issue are you encountering that this fixes? Providing more details, like screenshots/ exact browser version, will help us diagnose.

**Comment by dfmcphee** [comment]
I'm going to go ahead and close this since we don't have enough info. Feel free to re-open with more information if you are still running into an issue with this.
