### ISSUE TITLE
How to change Button background-color for make a color-picker pop-over component?

### ISSUE THREAD

**Issue by kadsystems** [Shopify/polaris-react-archive#276]
# Issue summary

Trying to make a color-picker component showing by button click I put ColorPicker inside a Popover triggered from a Button. And I want to make button showing selected color. I attach a code next, in this code I just try to make the button's background color to green. I trying to do next: 

```
<Popover
	active={this.state.buttonColorPicker}
	sectioned={true}
	activator={
		<Button
			onClick={() => { this.setState({buttonColorPicker: true}); }}
			style={{ 'background-color': 'green' }}
		>
		</Button>
	}
	onClose={() => { this.setState({ buttonColorPicker: false }); }}
>
	<Popover.Pane fixed>
		<Popover.Section>
			<ColorPicker color={{ hue: 120, brightness: 1, saturation: 1, }} onChange={() => { }} />
		</Popover.Section>
	</Popover.Pane>
</Popover>

```

![image](https://user-images.githubusercontent.com/27851002/36722665-331be872-1bbf-11e8-8b63-bc8a259addf2.png)

But it's not working. Hope there is any way to change background of Button.

**Comment by lemonmade** [comment]
There is no way to create a button with a background colour, as it would very likely conflict with the text contents of most buttons. In this instance, I'd recommend you not use the Polaris `<Button />` and instead write your own component based on `<button />`. Make sure that you also include a label for this button, otherwise a screen reader will not bye able to read out what this button is for; you can use `aria-label` or a visually hidden `span` if you don't want to actually show the label visually.
