### ISSUE TITLE
VueJs support

### ISSUE THREAD

**Issue by ghost** [Shopify/polaris-react-archive#36]
Hi Shopify team, 
Do you know if there will be a VueJs support in the future?

**Comment by lemonmade** [comment]
Hey @darkrubyist, we have no plans to release a Vue.js version of this library. We really like Vue.js, and strongly considered going with it in place of React, but decided against it in the end. We want to make sure we only provide a version of our components that we actually use internally (so that we keep them up to date, make them better over time, etc), so we're going to be going React-only for the foreseeable future.

**Comment by LasseRafn** [comment]
Would you potentially accept a PR to support Vue, or can I create my own repository with Vue support?

**Comment by tmlayton** [comment]
Hi @LasseRafn, you are welcome to create your own repository for a Vue.js version of this library.

**Comment by LasseRafn** [comment]
Great, thanks 👍

**Comment by juzser** [comment]
We're building Vue 3 version here: https://github.com/ownego/polaris-vue
I think it's 99% similar with React version and up to date. 

Hopefully it helps.
