### ISSUE TITLE
Create simple font-weight tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4598]

**Comment by lgriffee** [comment]
### Audit Findings 
I conducted a [quick audit of all `font-weight` instances](https://docs.google.com/spreadsheets/d/1QRIOeyZGNabZggZrrcLETRmjk9QIgC0utrcqxaXHo60/edit?usp=sharing) in polaris-react. 

Below is a brief summary of those findings:
| Value                       |  Instances        |
| ----------------------------- | ------------------- |
| 400                           | 9 results / 4 files |
| 500                           | 8 results / 7 files |
| 600                           | 9 results / 4 files |
| 700                           | 4 results / 2 files |
| ~~inherit~~                       | ~~1 result / 1 file~~   |
| ~~\--p-button-font-weight (500)~~ | ~~4 results / 3 files~~ |
| ~~\--p-badge-font-weight (400)~~  | ~~3 results / 3 files~~ |

*~~Strikethrough~~ values removed as part of cleanup PR (see below)

### Proposed Token Values 
Based on the values currently being used in the repo here are some possible token names:
| Value | Token Name (Option 1)        | Token Name (Option 2)           |
| ----- | -------------------- | ------------------------- |
| 400   | \--p-font-weight-400 | \--p-font-weight-regular  |
| 500   | \--p-font-weight-500 | \--p-font-weight-medium   |
| 600   | \--p-font-weight-600 | \--p-font-weight-semibold |
| 700   | \--p-font-weight-700 | \--p-font-weight-bold    

### Questions
- What naming convention should we move forward with?
- Are all these values meaningful? Should we condense/remove any?
- Should we include all possible font-weight tokens?

@sarahill I know you had both of these naming options in your [Density Improvements Figma file](https://www.figma.com/file/TQX4JBfDgAKUIlNvmWCdQv/Density-improvements?node-id=98%3A29727). Was there ever a decision made on which direction we want to go in with naming?

**Comment by alex-page** [comment]
This is excellent! Thanks @lgriffee!

Some thoughts for now. Can we remove `--p-button-font-weight` and `--p-badge-font-weight` today and just hard code them for now. Having two specific custom properties for font-weight values here is not super valuable. This would mean we can just find and replace font-weight: 400 when we have the tokens ready.

I am also curious if we can remove inherit… sometimes this isn’t needed any more..

**Comment by laurkim** [comment]
I had commented this in @sarahill's density document, but I think option 2 (`--p-font-weight-regular`) is more consistent with how people interact with font weights in Microsoft Word/Figma/Google docs. However, option 1 (`--p-font-weight-400`) would be consistent with the new proposed spacing tokens by using numeric indicators.

I'm leaning more towards option 2 because I immediately know what it'll look like if the token has `bold` in the name, as opposed to translating what `700` equates to. But I don't have that strong opinion on that because I think both have value.

**Comment by tjonx** [comment]
> * What naming convention should we move forward with?

This is a super interesting question. Even in typography world there's several different systems that were built (ie: Frutiger's Univers numeric system), but the proposed token name (Option 2) makes the most sense for designers. That's how we "speak", so it would feel more natural.

However, it is known that some fonts do not map weights the same way (ie: some fonts have `Book` or `Roman` instead of `Regular`/`400`) but I don't think it should be such a big issue.

**Comment by sarahill** [comment]
This looks great! 

My preference is option 1: `font-weight-400` `font-weight-300` etc. That being said it's a loose opinion and if the majority is leaning to 2 I'm ok with that. I agree option 2 is more natural. 

I was leaning to 1 because while semibold, bold are more natural, there are times where it becomes ambiguous. I could learn that 400 is normal weight and then scale from there kind of thing. There are some good points made above though for option 2.

**Comment by zecarlostorre** [comment]
I agree option 2 could be more obvious for designers, but I could also see the numeric systems work if we adopt the same values in our design tools. So designer would see 400 in figma rather than regular.

--

The other thought) is about range (I don't know if this is the moment for that, but I'll say it anyway).

I like that we have a limited set of 4, but they don't actually give us much distinction. 
For instance, the difference between Medium and Semibold isn't massive, so I wonder if this is another contributor to the sameness and lack of variety we see in the admin.

<img width="1533" alt="Screen Shot 2021-11-17 at 3 59 01 PM" src="https://user-images.githubusercontent.com/55551051/142235425-40938f14-3644-4747-9b7e-86b458b75e57.png">

I'm not proposing this, but it's just an example of what we could provide instead:

<img width="1499" alt="Screen Shot 2021-11-17 at 3 59 19 PM" src="https://user-images.githubusercontent.com/55551051/142235486-3c72128c-3d0b-4936-a8d6-0a9fb34da499.png">

**Comment by aaronccasanova** [comment]
I'm a fan of option 2. Here is a good MDN reference of [Common weight name mapping](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#common_weight_name_mapping)s. My concern with using integers in font-weight token names is that not all fonts are created equal. This isn't the best example but fundamentally illustrates my concern where both fonts have the same weights but drastically different outputs.

https://user-images.githubusercontent.com/32409546/142251406-33e2047e-8fa8-46c5-9f91-da66d5db5b6b.mov

If font weight tokens were mapped to idiomatic alias tokens we could assign the appropriate weight to match the desired look and feel rather than the technical numeric weight value.

This still holds true if we eventually move forward with @sarahill 's proposal for composite typography tokens: https://github.com/Shopify/polaris-react/issues/4600#issuecomment-970752689

**Comment by lgriffee** [comment]
Thanks everyone for your input on this! 🙏🏻 Y’all brought up a ton of great points. 🔥

Based on your feedback/input, I’m going to move forward with implementing the majority's preference for Option 2! 🚀 ✨

| Value | Token          |
| ----- | ------------------------- |
| 400   | \--p-font-weight-regular  |
| 500   | \--p-font-weight-medium   |
| 600   | \--p-font-weight-semibold |
| 700   | \--p-font-weight-bold  |

I'll defer range decisions to future work when we define our ideal token system. 👍🏻
