### ISSUE TITLE
Move --p-border-radius custom properties to polaris-react

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4611]

**Comment by lgriffee** [comment]
### Audit Findings 
I conducted a [quick audit of all legacy border token instances](https://docs.google.com/spreadsheets/d/1UhECaLn3s4NQ4VG0zg56VcCi17hVLIaxJRQtf9bGMbA/edit?usp=sharing) in polaris-react and web. 

Below is a brief summary of those findings:
#### Legacy Border Radius Tokens
| Name                       | Value                                                                                                      | \# polaris-react Instances     | \# web Instances        |
| -------------------------- | ---------------------------------------------------------------------------------------------------------- | ------------------------------ | ----------------------- |
| --p-border-radius-base         | 0.4rem                                                                                                 | 81 results / 37 files          | 84 results / 68 files   |
| --p-border-radius-full         | 50%                                                                                                        | 2 results / 2 files (only doc) | 3 results / 3 files     |
| --p-border-radius-slim         | 0.2rem                                                                                                     | 1 result / 1 file (only doc)   | 0                       |
| --p-border-radius-wide         | 0.8rem                                                                                             | 27 results / 13 files          | 120 results / 73 files  |

_Notes_
- It looks like we can remove `border-radius-slim` since it's not used in `polaris-react` or `web`

#### Other Legacy Border Tokens
This may not be in the scope of this current work but I wanted to bring it up in case we do want to move them to the new `_border` token file I created. 
| Name                       | Value                                                                                                      | \# polaris-react Instances     | \# web Instances        |
| -------------------------- | ---------------------------------------------------------------------------------------------------------- | ------------------------------ | ----------------------- |
| --p-banner-border-critical     | inset 0 0.1rem 0 0 var(--p-border-critical-subdued), inset 0 0 0 0.1rem var(--p-border-critical-subdued)   | 3 results / 3 files            | 1 result / 1 file       |
| --p-banner-border-default      | inset 0 0.1rem 0 0 var(--p-border-neutral-subdued), inset 0 0 0 0.1rem var(--p-border-neutral-subdued)     | 3 results / 3 files            | 0                       |
| --p-banner-border-highlight    | inset 0 0.1rem 0 0 var(--p-border-highlight-subdued), inset 0 0 0 0.1rem var(--p-border-highlight-subdued) | 3 results / 3 files            | 0                       |
| --p-banner-border-success      | inset 0 0.1rem 0 0 var(--p-border-success-subdued), inset 0 0 0 0.1rem var(--p-border-success-subdued)     | 3 results / 3 files            | 0                       |
| --p-banner-border-warning      | inset 0 0.1rem 0 0 var(--p-border-warning-subdued), inset 0 0 0 0.1rem var(--p-border-warning-subdued)     | 3 results / 3 files            | 2 results / 2 files     |
| --p-control-border-width       | 0.2rem                                                                                                 | 13 results / 7 files           | 4 results / 2 files     |
| --p-thin-border-subdued        | 0.1rem solid var(--p-border-subdued)                                                                       | 2 results / 2 files (only doc) | 0                       |

_Notes_
- It looks like we can remove `thin-border-subdued` since it's not used in `polaris-react` or `web`
- Originally I was going to recommend moving all the `--p-banner-border-*`s to the Banner component as `--pc-` but it looks like they are being used in `web` 😬

### Proposed Token Values 
Will be addressed in next iteration of this work. 

However, I think we can do the following in this iteration:
- Remove `border-radius-slim` since it's not used in `polaris-react` or `web`
- Depending on the scope of the work remove `thin-border-subdued` since it's not used in `polaris-react` or `web`

### Questions
- Should we also tackle cleaning up the other border legacy tokens since we're creating a new border token file?
