### ISSUE TITLE
Replace border-radius() function with tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4613]

**Comment by lgriffee** [comment]
### Audit Findings 
I conducted a [quick audit of all `border-radius()` instances](https://docs.google.com/spreadsheets/d/1UhECaLn3s4NQ4VG0zg56VcCi17hVLIaxJRQtf9bGMbA/edit?usp=sharing) in polaris-react and web. 

Below is a brief summary of those findings:
#### Border-radius()
| Name                       | Value                                                                                                      | \# polaris-react Instances     | \# web Instances        |
| -------------------------- | ---------------------------------------------------------------------------------------------------------- | ------------------------------ | ----------------------- |
| border-radius()            | 3px                                                                                                        | 17 results / 15 files          | 219 results / 183 files |
| border-radius(large)       | 6px                                                                                                        | 1 result / 1 file              | 36 results / 33 files   |

### Proposed Replacement Token Values 
- Create a `--p-border-radius-small` token to replace `border-radius()` since `--p-border-radius-base` already exists
- Create a `--p-border-radius-large` token to replace `border-radius(large)`

### Questions
- Should all these values be converted to rem for consistency with the other border radius tokens?

**Comment by lgriffee** [comment]
The previous token naming and values I proposed above are no longer going to work with the system implemented in https://github.com/Shopify/polaris-react/pull/4763:

| Name                       | Value                                                                                                      | 
| -------------------------- | ---------------------------------------------------------------------------------------------------------- | 
| border-radius-05           | 2px                                                                                                       |
| border-radius-1           | 4px                                                                                                       |
| border-radius-2           | 8px                                                                                                       |
| border-radius-3           | 12px                                                                                                       |
  | border-radius-4           | 16px                                                                                                       |
  | border-radius-5           | 20px                                                                                                       |
  | border-radius-half           | 50%                                                                                                       |

How do we want to deal with replacing the values of `border-radius()` since they don't fit in the scale we've implemented? 
| Name                       | Value                                                                                                      | \# polaris-react Instances     | \# web Instances        |
| -------------------------- | ---------------------------------------------------------------------------------------------------------- | ------------------------------ | ----------------------- |
| border-radius()            | 3px                                                                                                        | 17 results / 15 files          | 219 results / 183 files |
| border-radius(large)       | 6px                                                                                                        | 1 result / 1 file              | 36 results / 33 files   |

**Questions**
- Is there meaningful distinction between a border-radius of 3px and 2px/4px as well as 6px and 4px/8px?
  -  Should we keep all the values?
  - Should we try and replace the `border-radius()` values with the closest value in our new scale? 
- Is this something we don't want to decide now and should push off into the future? (and add all the values for now)

**Comment by johanstromqvist** [comment]
![image](https://user-images.githubusercontent.com/38329124/144497312-b40b9873-a440-4e44-abca-3db0cd7a6bae.png)

> Is there meaningful distinction between a border-radius of 3px and 2px/4px as well as 6px and 4px/8px?

The exact values are important for visually consistent nesting, so my gut says that it's risky to replace values (such as replacing 6px with 4px) without knowing how they are used and what the consequences are. It's unsatisfying, but my gut says that we'd better keep all the values for now. @zecarlostorre @sarahill @martenbjork

**Comment by johanstromqvist** [comment]
During our Design Language explorations we were looking at topics such as hierarchy, grouping, and shapes. That's where border radius values matter. That's where they do important jobs for merchants. José's recent exploration of badges, flags, and tags is another example, and I bet that the mobile team have opinions too.

The important thing imo is that our values are design decisions based on what we want to achieve visually in the Admin, and what that enables merchants to do. I don't think we have a strong opinion on what that is right now, but I think it's work that we need to do in 2022.

**Comment by alex-page** [comment]
> The exact values are important for visually consistent nesting, so my gut says that it's risky to replace values (such as replacing 6px with 4px) without knowing how they are used and what the consequences are.

@johanstromqvist @sarahill Could we do a quick design spike on this?

@lgriffee could share a pull request to show what these values look like against the components. You could review the visual regression test together to decide how large the consequences are. This might make it easier to decide what the values should be (if they should stay the same or match the spacing scale).

If we want to decouple from the spacing scale we should challenge the current spacing scale naming. It will get confusing having multiple naming patterns for referencing pixel values (font-size, border-radius, padding, line-height?).

**Comment by lgriffee** [comment]
Awesome, I'll go ahead and create a PR that temporarily replaces the 3px and 6px values with ones from the scale so we can review the the visual regression tests (@johanstromqvist and @sarahill I'll make sure to tag both of you—and I'll link each of the test cases from Chromatic in this thread so you can review them async).

That makes sense to me about challenging the current spacing scale naming (if we want to decouple the `border-radius` naming) so that all our pixel naming patterns are consistent. I can create a follow up discussion thread for the team to talk about it if we end up needing to decouple.

**Comment by lgriffee** [comment]
### Polaris-React Chromatic Regression Tests
- [Replace 3px border-radius values with 2px](https://www.chromatic.com/build?appId=5d559397bae39100201eedc1&number=9556)
  - 0 changes detected 👻 
  - But could affect up to 219 things in `web` not sure w/o testing there too
- [Replace 3px border-radius values with 4px](https://www.chromatic.com/build?appId=5d559397bae39100201eedc1&number=9559)
  - 1 change detected 🤔 
  - But could affect up to 219 things in `web` not sure w/o testing there too
- [Replace 6px border-radius values with 4px](https://www.chromatic.com/build?appId=5d559397bae39100201eedc1&number=9560)
  - 0 changes detected 👻 
  - But could affect up to 36 things in `web` not sure w/o testing there too
- [Replace 6px border-radius values with 8px](https://www.chromatic.com/build?appId=5d559397bae39100201eedc1&number=9563)
  - 0 changes detected 👻 
  - But could affect up to 36 things in `web` not sure w/o testing there too

Does `web` have Chromatic regression testing as well? If it does, it might be worth creating a branch in `web` to test these changes if they aren't impacting things in `polaris-react` 🕵🏻‍♀️ I also wonder why we're not seeing more changes in `polaris-react` for these...I did make some big changes to the values which were detected—see commit 35d1161 ([Chromatic tests](https://www.chromatic.com/build?appId=5d559397bae39100201eedc1&number=9552)) and 946a026 ([Chromatic tests](https://www.chromatic.com/build?appId=5d559397bae39100201eedc1&number=9553)).

**Comment by lgriffee** [comment]
`Web` does have Chromatic UI regression testing! 🎉 I'm going to open a branch there and do these same tests in web to see if we get some more conclusive results 🔎 👀 Will post links and results in this thread!

**Comment by lgriffee** [comment]
_Including y'all here since you are Token Group Advocates  for border-radius()_
@zecarlostorre @aaronccasanova @martenbjork @sarahill @heyjoethomas 

### Web Chromatic Regression Tests
- [Replace 3px border-radius values with 2px](https://www.chromatic.com/build?appId=6054e7fc826ed700218e4b3b&number=21781)
  - 0 changes detected 👻

So it turns out that Chromatic in web doesn't work the way we want it to for testing visual regressions because web's Storybook doesn't include all components that are live in web right now (if the components are not in Storybook they will not be tested for visual regression by Chromatic). 

As you can see in the link above, when I tried running the same first regression test in web nothing changed 😭 And when I tried an even bigger change of converting `border-radius()` values across web from 3px to 30px Chromatic didn't detect anything even though I could see that there were visual changes happening in my spin instance (see below). 

<img width="766" alt="Screen Shot 2021-12-09 at 10 25 11 AM" src="https://user-images.githubusercontent.com/21976492/145473522-d3804847-6312-4bf6-88ef-99b670c832db.png">


<img width="762" alt="Screen Shot 2021-12-09 at 10 15 35 AM" src="https://user-images.githubusercontent.com/21976492/145473539-2e4b0125-ed93-4291-a323-3b156e12541c.png">

Web doesn't have enough Storybook coverage for us to understand the effects of changing `border-radius()` values. 

Because of this and our upcoming end of year break, I propose for now we follow @johanstromqvist's advice and keep `border-radius()` and `border-radius(large)` values in our tokens for now and follow up this work with another phase to create our ideal tokens. 

> The exact values are important for visually consistent nesting, so my gut says that it's risky to replace values (such as replacing 6px with 4px) without knowing how they are used and what the consequences are. It's unsatisfying, but my gut says that we'd better keep all the values for now. 

I will create a follow up issue for this future work on border-radius.
