### ISSUE TITLE
Replace `shared/_typography.scss` with react component

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4932]
Replace shared/_typography.scss with react component if effort is minimal, otherwise wait add to create type project.

**Comment by aaronccasanova** [comment]
We've decided to deprioritize this to a v9.X.X follow up task. The proposed `Typography` component in PR #4978 is based on backward compatibility instead of a future facing API we would encourage folks to use. We intend to continue exploring this idea of consolidating all typographic styles, mixins, and utilities to a single component, but need to reprioritize our focus on tasks that have an immediate impact on the v9.0.0 release.

**Comment by alex-page** [comment]
This is going to be a part of the layout work. Closing for now.
