### ISSUE TITLE
polaris.shopify.com includes a table of tokens with copy/pastable values

### ISSUE THREAD

**Issue by lgriffee** [Shopify/polaris-react-archive#4936]
- [ ] Explanation of breaking changes in v9
- [ ] Explanation of tokens
- [ ] Where do tokens live?
- [ ] Copy passable table of tokens
- [ ] Token examples?

**Comment by jjgali** [comment]
Currently looking at the best place for this documentation to live. A couple top considerations:
- a separate top level item (like components)
- a section within the Design page (since that's where a lot of things we're building tokens for already live)

Will weigh the advantages of both, and list any other options that present themselves.

**Comment by alex-page** [comment]
@martenbjork @jjgali moving this issue out to an epic https://github.com/Shopify/polaris-react/issues/5073
