### ISSUE TITLE
Remove public scss api

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4980]
- [x] Remove the [src/styles/_public-api.scss](https://github.com/Shopify/polaris-react/blob/main/src/styles/_public-api.scss) file
- [x] Remove the [build script](https://github.com/Shopify/polaris-react/blob/main/loom.config.ts#L117-L121) that copies the public API to the npm package
- [x] Document the removal of the public API

**Comment by BPScott** [comment]
This was the result of a chat I had with Alex earlier. Here's the context for why:

It's great to see the removal of sass functions, but I had a concern with how we were going to teach this to consumers. As it currently stands, we'd be able to remove a bunch of stuff from the src/styles folder (and thus from the public sass api), however we wouldn't be able to remove everything as part of the v9 release. This meant that:

- As part of the v9 we'd teach consumers "we've deleted half of the public sass api, here are copies of the functions you removed to drop into your app".
- Then we'd have to remove the other parts of the sass api in v10
- And as part of the v10 release we'd teach consumers "we've deleted the other half of the public sass api, here are copies of the functions you removed to drop into your app".

That feels kinda clunky, it means consumers have to two similar migrations at different points in time and it locks us into having to do any refactoring as part of a breaking change - we'd be stuck working on a v10 branch instead of merging PRs into main.


Instead, This issue proposes removing public access to our sass in v9. Some sass mixins/functions would remain, but consumers would not be able to access them. This would mean that:

- The polaris team would be free to refactor / remove them whenever as they are implementation details of how we build this package, instead of a public API that must be maintained until the next major version. 
- We'd get folks to migrate away from the public api in one go, instead of making it be a two-phase process - that's less work for consumers and us. As part of the v9 we'd teach consumers "we've removed the entire public sass api, here are copies of the functions you removed to drop into your app". There is nothing to be done in v10.
- Removal or refactoring of any sass mixins / functions we use internally can occur when we want in minor releases, with PRs targeted against main as they're internal implementation details instead of a public API we must maintain. The polaris team becomes free to move away from sass at their leisure.
- Removing the public sass API means that we don't have to worry about producing mixins that interop between node-sass and dart-sass (because consumers could use either) go away because there is not way to externally consume our sass mixins/functions. We only need to worry about what version of sass we're using locally. Concerns about dart-sass interop go away immediately.We'd be free to migrate this repo to use dart-sass at any point in time
