### ISSUE TITLE
Consolidate Figma UI Kit

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react-archive#5397]
1 kit to rule them all 🔥

**Comment by martenbjork** [comment]
I would consider calling it "Polaris". When Emma, Rahil and I have been developing the Figma plugin, we've frequently searched for the current kit and we can _never_ find it.

**Comment by heyjoethomas** [comment]
@martenbjork Yes. I think I would go in a slightly different direction though. Instead of a single file I would do the following:

1. Polaris: Styles (color, type, shadows, spacing, grids) - These are all separate right now.
2. Polaris: Icons
3. Polaris: Components
4. Polaris: Views - This would be a new file that has reference views that designers can use as a starting point. So entire screens of key views. Often designers have to rebuild things from scratch or hunt files.

Thoughts?
