### ISSUE TITLE
'Select all' option on product picker

### ISSUE THREAD

**Issue by jmiguelsamper** [Shopify/polaris-react-archive#54]
Hello,

we use the Embedded SDK Product Picker component and it is fantastic, saving us a lot of developing time.

However, when multiple selection is active, we miss a 'Select all' option that would save merchants the tedious work of selecting all products one by one:

![Product Picker](https://cdn.shopify.com/s/files/1/0652/1337/t/34/assets/multiple.png)

As a lot of work is currently being done with Polaris and this is a _related_ component, could you consider adding that feature? Thanks in advance.

**Comment by mfaisaljs** [comment]
hi, any updates on this. i am also looking for this feature and i believe its a basic requirement when a store can have over 100 products and they have to select them all manually

**Comment by kaelig** [comment]
Thanks for your suggestion! We can't give a release date at this point but we've added this feature into our backlog.

**Comment by ry5n** [comment]
Hi @jmiguelsamper. I wanted to let you know that we’re still tracking this feature request as part of our backlog, but we’re working on other priorities at the moment.

Since we can’t offer a timeline, I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜

**Comment by jmiguelsamper** [comment]
Hi Ryan,

Thanks for the update.

Would you consider accepting a PR for this?

**Comment by ry5n** [comment]
We aren’t accepting PRs… yet. BUT, we’ve committed to [making the react library fully open source](https://polaris.shopify.com/whats-new/roadmap#section-making-polaris-react-truly-open-source), and we’re working on it as we speak.

**Comment by cheetong** [comment]
any chance for this to be developed? It really save a lot of time on selecting the products. Imaging I have to click 200+ products one by one.
