### ISSUE TITLE
Create a top-level `tscofig.json` for the entire monorepo

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5432]

**Comment by BPScott** [comment]
Additional requirements from #5424:

- This root tsconfig.json file should used project references to reference the individual project configs.
- Create a `yarn run type-check` root level package.json script that runs `tsc --build`, so that it runs type checking across all projects in one go
- Run `yarn run type-check` as part of CI
- BONUS: create a `tsconfig.base.json` that all project-level tsconfigs can inherit from as they'll should all have pretty much the same config.
