### ISSUE TITLE
Consolidate, remove and add values to the color tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5456]
## Minor/Patch Changes

- #5885 
- #5990 
- #5986 
- #5991 
- #5992 

## Breaking Changes

- #5993 
- #5994 

## Documentation

- #5995

**Comment by IlanaB** [comment]
FYI I think the deprecation warning for `CustomProperties` is creating a lot of noise in component tests on web now indirectly since we're using Polaris components that are still using it. To test I removed all uses of `CustomProperties` in web and still see a ton of warnings when I run tests on different components. IMO it would be preferable to remove all uses in Polaris before adding the warnings for this reason.

Is there an ETA on when the Polaris components will be updated to remove it?

Example test run in web after removing all uses of `CustomProperties` there:

<img width="674" alt="Screen Shot 2022-06-22 at 11 23 40 AM" src="https://user-images.githubusercontent.com/3604481/175069109-c9375760-9c61-4bad-85bd-8f38e0d807c3.png">

**Comment by alex-page** [comment]
Final release with v10.
