### ISSUE TITLE
[Polaris website refresh] Explore best way to author jsx/md content

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react-archive#5467]
Our needs:

- Writing content
- Adding images 
- Adding videos
- Embedding Polaris examples
- Embedding arbitrary jsx
- ⚠️ Ability to extract content in a modular and context-aware way (to the API)

### mdx

👍 Theoretically mixes markdown and jsx seamlessly.
👎 Feels pretty hacky and fragile. I found it difficult to get eslint and prettier to play nice.

```tsx
# Title
Some markdown

<SomeComponent />

Some more markdown
```

### Plain tsx

👍 Native. Straight forward. Easy to mix HTML and React.
👎 Requires HTML knowledge. Less readable than markdown. Lots of room for divergence. 

```tsx
function Page() {
  return (
    <>
      <h1>Title</h1>
      <p>Just some text</p>

      <CustomComponent />
    </>
  )
}
```

### react-markdown
Using [react-markdown](https://github.com/remarkjs/react-markdown) to mix React and markdown content.

👍 Pretty straight forward. Easy to puzzle pieces together.
👎 If written inside the return function, Prettier will try to indent the markdown which breaks it. Therefore it needs to be pulled out into separate `const`s. A little messy.

```tsx
const intro = `
Welcome to the blog post!
`;

const end = `
That's all folks!
`;

function Page() {
  return (
    <>
      <ReactMarkdown>{intro}</ReactMarkdown>
      <CustomComponent />
      <ReactMarkdown>{end}</ReactMarkdown>
    </>
  );
}
```

We could iterate on this to abstract the internals away:

```tsx
const intro = `
Welcome to the blog post!
`;

const end = `
That's all folks!
`;

const Page = createPage(
  intro, 
  <CustomComponent />,
  end
);

export default Page;

```

**Comment by alex-page** [comment]
```
---
specialComponent: special.md
---

# Title

Some markdown

Some more markdown
```

**Comment by BPScott** [comment]
When wrangling the alpha experiences site I spent a lot of time thinking about this. We didn't really want the idea of allowing arbitary jsx content, instead there'd be a selection known "custom blocks" that markdown authors could use.  I really liked the idea of plain markdown but with fenced codeblocks counting a blob of json (acting as the "props" for your custom block) that then got processed and transformed into special components. I got this working in ruby in https://github.com/Shopify/polaris-styleguide/pull/3699, but you'd be able to do the same thing in JS with `remark`. This is neat as it's still pure real markdown - it's not inventing a new formatting language so all your markdown handling tools (linters etc) work as expected because of the usage of `json:` as a prefix for the "language" of the fenced code block you even got syntax highlighting of the block.

So you could author something like:


~~~md
## I am some plain markdown

I am some paragraph

```json:content-block-resource-links
[
  {
    "title": "Retail staff interviews",
    "href": "https://docs.google.com/presentation/d/1P8FWNQ6NPcMiwcSpXCuQOSubu4rzFMWcRNneVWoivks/edit?usp=sharing",
    "description": "This deck provides context on the unique roles &amp; responsibilities of people working in the physical retail context in order to uncover areas of opportunity."
  },
  {
    "title": "POS onboarding flow",
    "href": "https://www.figma.com/file/qDDdizhQKP2mktBgzM4yfP/Onboarding?node-id=0%3A1"
  }
]
```

 back to plain markdown here *bold text*
~~~

Using a markdown AST transformer you can read fenced code blocks with specific language and transform them into some arbitrary HTML, and then continue the rest of the markdown as normal so your compiled output became

~~~html
<h2>I am some plain markdown</h2>

<p>I am a paragraph</p>

<div class="my-content-block-resource-links">
<ul>
<li><a href="https://docs.google.com/presentation/d/1P8FWNQ6NPcMiwcSpXCuQOSubu4rzFMWcRNneVWoivks/edit?usp=sharing">Retail staff interviews</a>: This deck provides context on the unique roles &amp; responsibilities of people working in the physical retail context in order to uncover areas of opportunity.</li>
<li><a href="https://www.figma.com/file/qDDdizhQKP2mktBgzM4yfP/Onboarding?node-id=0%3A1">POS onboarding flow</a>
</ul>
</div>

<p>back to plain markdown</p>
~~~

**Comment by martenbjork** [comment]
Came up with a new proposal for this: https://github.com/Shopify/polaris/pull/5660

**Comment by martenbjork** [comment]
New thing from Stripe: https://markdoc.io/ via @romellogoodman

**Comment by martenbjork** [comment]
Test implementation of Markdoc: https://github.com/Shopify/polaris/pull/5821
