### ISSUE TITLE
CDN-hosted webpack JS bundle?

### ISSUE THREAD

**Issue by sogko** [Shopify/polaris-react-archive#58]
Hi guys, awesome work on Polaris. Looking forward to migrate our apps from our in-house custom Shopify UI component clone library to polaris really soon.

In addition to the stylesheet hosted on Shopify's CDN, any plans to have the webpack-bundled JS file hosted on CDN as well? 

It would allow developers to have a smaller app bundle -> faster downloads -> better UX for merchants.

Currently, we have our Shopify apps built on React as well, and we have external libraries set up as [webpack externals](https://webpack.github.io/docs/library-and-externals.html) to reduce our app size (e.g `react`, `react-dom`, `react-router` etc are hosted on cdnjs).

Having `polaris` library hosted on CDN as well would really help to extract UI components out from our app bundle and only have app/business logic left, which would greatly reduce the app size. And it being hosted on `shopifycdn` would be ideal.

An alternative would be to submit polaris library to other CDNs (e.g [`cdnjs`](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) ) and have them host the library.

Would love to hear your thoughts.

Cheers!

**Comment by lemonmade** [comment]
Hey @sogko, thanks for reaching out. We thought about this a fair bit before launching. We ended up deciding not to do a CDN JS bundle for a few reasons:

1. It ended up being really hard to tell people how to use Polaris. Are you using NPM? We have one solution, that might vary if you can import CSS files. No NPM, but want to use React? another option. No desire to use React? another. We couldn't find a good way of messaging this.

2. If someone wants to use React, almost every resource they will find will push them in a direction where they end up using NPM and a built tool like Webpack. At that point, the better experience is bringing in Polaris via NPM.

3. A UMD build requires that every dependency and component be packaged and downloaded for every app. This can lead to unnecessary duplication of JS and inclusion of components you don't need, which is not necessarily the case with tree-shaking bundlers like Webpack.

4. We are more at risk of issues with React/ React DOM version differences causing issues with our library since we just rely on an (unversioned) set of globals for those libraries.

All that said, it's not a slam dunk. If you are interested in having this split, I would recommend using Webpack's CommonsChunkPlugin/ vendor DLL to split out the `@polaris/shopify` imports into a separate bundle.
