### ISSUE TITLE
Modal should close by clicking on background 

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react-archive#5834]
## Issue summary

The Polaris modal doesn't close when clicking on the background and our guidance recommends against clicking the background to close. 

## Expected behavior

Merchants should be able to close the modal by either selecting the close button, pressing the escape key, and clicking the background. 
<img width="764" alt="slack-imgs-1" src="https://user-images.githubusercontent.com/47306956/169077287-8f33a41f-8cd3-4a63-b63c-2b9299bc9fe2.png">

## Done when

The modal behavior has been updated
The style guide guidance has been updated

**Comment by jjgali** [comment]
Some discussion around this topic surfaced in Slack, and I'm adding it here so it's documented. 

## Concerns about closing on background click
There is a concern that allowing a modal to close on background click would change the definition of what a modal is. 

Polaris currently defines a modal as:
> Overlays that require merchants to take an action before they can continue interacting with the rest of Shopify.

If we allow merchants to exit a modal by clicking the background, we are allowing them to continue without taking an explicit action. For example, they could accidentally click out of a modal and mistakenly circumvent an important action.

If we do make this change, we need to redefine what a modal is as well. Should modals require merchants to take action?

Also a note that redefining a modal to not require action may invalidate some existing use cases for modals where we need a merchant to intentionally take action before proceeding.

## Rationale in favor of closing on background click
- Clicking the background to close is a common, expected behavior.
- Clicking the background to close is still an action; it's essentially an undo.
- The current behavior/recommendation may be a classic case of Polaris documentation being too restrictive.

## Proposed solution
### Short term
In the short term, we could:
- Update the documentation to be less restrictive. For example, modals should:
     > - Require that merchants take an action **or dismiss the modal**.
     > - Close when merchants press the `X` button, the `Cancel` button, the `Esc` key, **or** click or tap the area outside the modal.
- Default to the modal being dismissible if you click the background, but give product teams the option to not make it dismissible, if an explicit, intentional action is required.

### Long term
In the long term, we could consider using different modals for different scenarios. An example of this would be the way Material Design uses [modal variants](https://material.io/components/dialogs#confirmation-dialog) to determine usage.
<img width="624" alt="Screen Shot 2022-05-24 at 11 46 09 AM" src="https://user-images.githubusercontent.com/77791660/170089285-8dca2a06-54c9-4e35-81bf-51af44114df1.png">

**Comment by jjgali** [comment]
> Default to the modal being dismissible if you click the background, but give product teams the option to not make it dismissible, if an explicit, intentional action is required.

@kyledurand What are your thoughts on this? Is this a possible solution?

**Comment by kyledurand** [comment]
It's doable, do you have a name for the property that would be passed in to modal to prevent close on background click?
