### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components)

### ISSUE THREAD

**Issue by Epiffany** [Shopify/polaris-react-archive#6372]
Why'd you strip out the component categories from the left sidebar list?

**Comment by alex-page** [comment]
Hey @Epiffany, we definitely understand that some people found the categories useful. Other folks had a hard time remembering which categories the components were in. This change was to simplify the navigation and make it easier to find components by name alphabetically instead of remembering what category they are in.

I am going to close the issue but I would be happy to re-open it with additional context.
