### ISSUE TITLE
[polaris.shopify.com] Copy all tokens

### ISSUE THREAD

**Issue by nickradford** [Shopify/polaris-react-archive#6436]
Feature request: Provide a way to copy all of the color (and frankly all the other tokens), so that app developers that would like to brand certain Polaris components can do so more easily.

**Comment by alex-page** [comment]
Hey @nickradford we have the [polaris-tokens](https://github.com/Shopify/polaris/tree/main/polaris-tokens) npm package which provides all of the values from Polaris. Is that sufficient? Could you describe what you are trying to accomplish?

Maybe we could provide a better entry point for developers on the /tokens page of polaris.shopify.com?

**Comment by nickradford** [comment]
Thanks for the link to that package! Though, I don't think that would be sufficient. 

I don't have a hard use case for this, but there are parts of an app I work on where we discovered the tokens via the browser inspector, and then redefined those values in our app to help brand continuity between Polaris components and custom code.

For example
```css
* {
  --p-focused: var(--our-custom-focus-color);
}
```

We do the same thing for other tokens on a number of other Polaris components. To simplify this process (as new components are added over time), it would be nice to copy all of the tokens and their default values as CSS, which we could put into our app CSS and customize as needed.

**Comment by alex-page** [comment]
Ahhh I see, thanks @nickradford!

Theming with Polaris is something we need to build API's so that you can easily inject app brands into Polaris without concern for breaking changes. This approach you are taking isn't recommended but it works! Glad you can create an awesome experience with it. As this isn't recommended and we need to build API's for theming, I am unsure if copy paste of all the tokens would be the best long term approach.

I would recommend using the CSS output of `polaris-tokens`. This is going to be versioned and documented with our changelog. Let me know if the output of the [@shopify/polaris-tokens@5.4.0/dist/css/styles.css](https://unpkg.com/@shopify/polaris-tokens@5.4.0/dist/css/styles.css) file is what you need.

**Comment by nickradford** [comment]
Happy to work with y'all as you consider theming implementations!

I'll take a look at that CSS and see if that would fit the possible need we have 😃

**Comment by alex-page** [comment]
I'll close the issue for now. Feel free to reopen if the CSS file isn't what you need.
