### ISSUE TITLE
Icon for "Plan" in settings

### ISSUE THREAD

**Issue by dGoligorsky** [Shopify/polaris-react-archive#6501]
## Component name
plan_major

### Short intro description (try and keep to two sentences):
The icon for "Plan" in settings is currently a wallet, which is the `balance_major` icon.
Proposing a new icon, "plan_major" to replace the use of the balance icon to represent Plan.

![image](https://user-images.githubusercontent.com/5823560/177294912-4162be9d-78f7-45bd-a159-9e6a8c403f62.png)

<img width="735" alt="plan_major_paths_screenshot" src="https://user-images.githubusercontent.com/5823560/177295009-36a54b77-945f-4d87-8fdc-f0b24e7e5537.png">

SVG code, 245 bytes:
`<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" focusable="false" aria-hidden="true"><path d="M11 2a2 2 0 0 0-2 2v3H7a2 2 0 0 0-2 2v3H3a2 2 0 0 0-2 2v5h16a2 2 0 0 0 2-2V2h-8Zm0 2h5v3h-5V4ZM7 9h5v3H7V9Zm-4 5h5v3H3v-3Z" fill=""/></svg>`

**Comment by ghost** [comment]
👋 Thanks for opening your first issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md).

**Comment by raquelbreternitz** [comment]
Hi @dGoligorsky! Thanks for putting work towards contributing this icon to Polaris! This was super easy for me to grok, so I appreciate it. :)

I have a couple questions ahead of submitting the PR:
- ~What's the goal for changing this icon? Is the "balance" icon used elsewhere, or is it just a clearer description of what to expect on that page (tiered subscriptions I'm assuming)?~ Read the original issue, got it!
- It looks like it's 1px off on the keylines, which I think makes sense for visual balance of the steps, but I was wondering if this icon would appear non-vertically? I was chatting with @heyjoethomas and he suggested aligning it so the bottom has the pixel difference, since it's bottom-weighted, so it can feel more optically aligned in its current iteration.
- Thoughts on rounding the edges on the exterior, as well, to better fit our general icon style? I don't think it loses its readability as steps. I personally don't hate curving the interior spaces as well, if you extend them a pixel (unless you're worried they'd end up feeling too blobby overall). We're trying to be more intentional about adhering to our stylistic guidelines (2px, curved edges, etc.) unless it really doesn't work visually.

Attached some explorations but I'm not married to them (excuse my quick and dirty prototyping):

<img width="323" alt="Screen Shot 2022-07-05 at 2 45 37 PM" src="https://user-images.githubusercontent.com/13204374/177404081-0352bef5-f3c6-4a11-9e5b-a8b8733364b0.png">
<img width="298" alt="Screen Shot 2022-07-05 at 2 46 12 PM" src="https://user-images.githubusercontent.com/13204374/177404082-7a445b9b-5716-4b93-bce3-b96477fb02f7.png">
<img width="427" alt="Screen Shot 2022-07-05 at 2 36 41 PM" src="https://user-images.githubusercontent.com/13204374/177404080-d8b685e1-526d-4198-a35e-4bb669894016.png">

- Is there a reason the steps are left-to-right versus right-to-left? I assume it's because the plans grow in $$, but I was thinking it feels better, optically, to flip it horizontally  — probably because we read left-to-right so it feels more balanced? (And maybe it would subtly influence merchants to want to be at the top tier? 🤔 I'm probably traveling here.) Just I thought I'd pitch it for people's reactions):

<img width="316" alt="Screen Shot 2022-07-05 at 2 52 54 PM" src="https://user-images.githubusercontent.com/13204374/177405464-c38db4d2-0844-4158-8bfa-50deaa1c14cf.png">

- Would you imagine there would be a future use case for making this as a minor icon, as well? I assume not, but worth considering when we're adding a major icon whether we should just add a minor as well.

- What about other uses in the admin? Would this icon work in other instances for other teams to use?

Looking forward to hearing your thoughts!

**Comment by dGoligorsky** [comment]
Thanks for your notes and exploration, @raquelbreternitz !

- I'm good with shifting the icon up one pixel 👍 
- I left the hard edges on the bottom left and top right of the stairs to make them feel more grounded. But I'm ok with rounding the outside edges if it would make it feel like a better fit in the system.
- The strokes do follow the guidelines (2px, center stroke, 1px radius) which leads to a sharp inside angle. Don't really want to round the inside shapes since they're not strokes, they're the space created by the strokes. Made a little example thing—
![image](https://user-images.githubusercontent.com/5823560/177743244-83c9d73a-7592-4b44-8258-3e7beae6ecdb.png)
![image](https://user-images.githubusercontent.com/5823560/177743272-0348beed-518a-4b93-8992-782defce09e5.png)
- I'd like to stay with the steps going "up-and-to-the-right" for growth! 📈 (A side note, the icons tend to be up/right focused. Right: checkout, shipping. Up+Right: payments, apps, files, policies. All others are neutral, except for Brand, which is down/right)
- Happy to create a minor icon 😺 
- Not sure how teams might use this icon in other instances, but I think it's ok for this to just represent Shopify Plans. Things like a shipping truck or a shopping cart icon will inevitably see other uses outside the settings card because they're so literal and archetypal. Plans is less literal and I don't feel like there's an archetypal way to represent it. Wallet has too many potential meanings— payments, payouts, buy, sell, billing, fee, tax... and of course not all people and cultures have that leather bi-fold thing!

Let me know what you think and I'll put together the minor as well!
![image](https://user-images.githubusercontent.com/5823560/177748227-79087c93-6fff-46ae-a1cf-3ad7b19ebba2.png)

TYTY

**Comment by raquelbreternitz** [comment]
😍 Thanks for explaining all this, that makes sense! It gets tricky knowing when something is "interior space" and when something is a cut-out stroke, haha.

This feels like it landed in the right place to me @ a pixel up with rounded exterior and sharp interior 👏 

@heyjoethomas good to merge?

**Comment by dGoligorsky** [comment]
Nice nice, 
Let me make the minor icon. 
Then I'll create the production <svg> for the major and minor and add it here.

**Comment by dGoligorsky** [comment]
Here we go!

### Plans Major 🐆  
_276 bytes_

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" focusable="false" aria-hidden="true">
<path d="M11 1a2 2 0 0 0-2 2v3H7a2 2 0 0 0-2 2v3H3a2 2 0 0 0-2 2v3c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-6Zm0 2h5v3h-5V3ZM7 8h5v3H7V8Zm-4 5h5v3H3v-3Z" fill=""/>
</svg>`

<img width="786" alt="plans_major_xray" src="https://user-images.githubusercontent.com/5823560/177996880-b52f7b21-56f3-4f0a-a6c5-cea396757b83.png">



### Plans Minor 🐈 
_276 bytes_

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" focusable="false" aria-hidden="true">
<path d="M11 3a2 2 0 0 0-2 2v2H8a2 2 0 0 0-2 2v2H5a2 2 0 0 0-2 2v2c0 1.1.9 2 2 2h10a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2h-4Zm0 2h4v2h-4V5ZM8 9h4v2H8V9Zm-3 4h4v2H5v-2Z" fill=""/>
</svg>`

<img width="791" alt="plans_minor_xray" src="https://user-images.githubusercontent.com/5823560/177996905-084cef6a-ceb1-4b0b-94d0-dc24fd317636.png">


The Major icon in context—

![image](https://user-images.githubusercontent.com/5823560/177997725-82a34521-e43a-48bb-b3ea-735050289198.png)

### Files (the icon is black, so might be hard to see below if you're in dark mode)

![plans_major](https://user-images.githubusercontent.com/5823560/177998232-3d577dbb-0437-4ed3-a68c-78e7f107e8d6.svg)

![plans_minor](https://user-images.githubusercontent.com/5823560/177998229-60823e5c-c46f-40f7-a9a5-92b682b282bc.svg)

**Comment by dGoligorsky** [comment]
@raquelbreternitz @heyjoethomas 

Hey ya! Just wanted to be sure you have everything you need from me here?

Let me know if you'd like me to support with any next steps to implement this 😃

**Comment by heyjoethomas** [comment]
Hey @dGoligorsky this looks great. Just need to get a PR up to get them added to the Polaris-React repo. Docs for that can be [found here](https://polaris.shopify.com/contributing/icons).

**Comment by dGoligorsky** [comment]
Thanks @heyjoethomas !

- Opened the PR #6649 per the documentation you shared 
- Created a branch and review request in the Figma UI Kit

**Comment by heyjoethomas** [comment]
Just shipped in Figma
