### ISSUE TITLE
Publish the `Style guide to the style guide` doc on the website

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#6693]
Take this [google doc](https://docs.google.com/document/d/1zVDsHIWhoir2svRjdtSdRbD_ruTz3K1nAJcQLGPVQwM/edit#heading=h.ni67tdntu9cr), edit the content and publish it publicly to the site

**Comment by selenehinkley** [comment]
Adding a new task to this issue based on a pain point we've experienced while shipping the new patterns pages on Polaris.Shopify.com:
- [ ] Create lightweight visual design guidance for pages on Polaris.Shopify.com to help designers and builders align and build faster when shipping new pages to the site.

The first step may not be to publish publicly on the site with our current style guide (which is primarily content guidance), but I wanted to keep these two tasks together since I think the information belongs together.

FYI @martenbjork @johanstromqvist @@bernardojoaogarcia @raquelbreternitz @tracytees @nblloyd @SeanyB

**Comment by raquelbreternitz** [comment]
> Adding a new task to this issue based on a pain point we've experienced while shipping the new patterns pages on Polaris.Shopify.com: [] Create lightweight visual design guidance for pages on Polaris.Shopify.com to help designers and builders align and build faster when shipping new pages to the site.

Love that, happy to take it on when relevant.
