### ISSUE TITLE
Icon contribution template for SVG code

### ISSUE THREAD

**Issue by jjgali** [Shopify/polaris-react-archive#6783]
## Feature request summary

As raised by @dGoligorsky in discussion https://github.com/Shopify/polaris/discussions/6762:

> For icon contributions, curious if you want to add a template for the svg code since it can often have attributes we don't need. Something like `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="<!-- your vector path here -->" fill="#5C5F62"/></svg>` ?

## Rationale

This template would simplify the SVG code since it can often have attributes we don't need.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
I am not a huge fan of this. It might work for some designers but for others this could be quite intimidating trying to learn SVG code. Sometimes there are multiple paths or shapes.

**Comment by dGoligorsky** [comment]
@alex-page The reason I bring it up is because when I was contributing, I

- wasn't sure whether to use `viewBox` or `width`/`height`. 
- wasn't sure if I should include the `focusable="false" aria-hidden="true"` attributes in the svg code
- wasn't sure if I should keep the `fill` attribute empty (`fill=""`) or include it at all, or what hex to use if I used a hex (`fill="#5C5F62"`)

Agree, it's better to have a contribution than to intimidate people away from contributing. But maybe a reviewer can help clean up the svg code before merging.

**Comment by alex-page** [comment]
@dGoligorsky these are excellent points. We should add them to the guidance and couple that with a reviewer looking over the SVG code. In the future we might be able to automate this but for now that makes a lot of sense.
