### ISSUE TITLE
Button Component - Icon on the right for external links

### ISSUE THREAD

**Issue by stephenshop** [Shopify/polaris-react-archive#6799]
## Feature request summary

Would it be possible to add the ability to align the icon of the button on the right hand side for buttons intended to open external links.

Such as:
<img width="210" alt="Screenshot 2022-07-28 at 16 26 36" src="https://user-images.githubusercontent.com/103115762/181546554-47e1e022-05ef-4532-9159-a82dbb2afc2a.png">

## Rationale

From a consistency point of view, external links add the icon on the right hand side.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by martenbjork** [comment]
Hi Stephen! I don't have strong opinions myself, but I'll ping @sarahill and link to this discussion on the use of external links: https://github.com/Shopify/polaris/discussions/6558

**Comment by joellesasseville** [comment]
For more context: 

In SFN (first party app), we often need to link merchants to external services or are forced to open admin pages in another tab, due to technical limitations. Following accessibility best practices, we want to clearly display this redirection to merchants, and want to remain consistent with the icon placement (on the right).
From a hierarchical standpoint, the primary and basic buttons are the most logical option in these instances.

Here are a couple example where external icons would be useful in buttons : 
<img width="395" alt="Screen Shot 2022-07-28 at 10 36 51 AM" src="https://user-images.githubusercontent.com/87651175/181563280-26fa3bbc-1861-4a47-bfbc-f3e992feb7b0.png">
<img width="1193" alt="Screen Shot 2022-07-28 at 10 36 14 AM" src="https://user-images.githubusercontent.com/87651175/181563307-c8d44b53-6480-42d8-bb8d-5dfe2b78aeb0.png">
<img width="1581" alt="Screen Shot 2022-07-28 at 10 33 51 AM" src="https://user-images.githubusercontent.com/87651175/181563319-834c2f32-804a-41f0-9d78-0a64902dca3e.png">

**Comment by alex-page** [comment]
> Buttons going to external pages is an antipattern. I don't think we should scale this. Clicking a button should be a high trust moment.
> 
> In your situation what is happening? Is the page that the button takes the user to look and work the same as the admin? Does the user know they are going to a new website? Does the experience change dramatically?
> 
> Looking at the screenshots I believe these should be links and not buttons.

From the discussion https://github.com/Shopify/polaris/discussions/6558

**Comment by sarahill** [comment]
I agree with @alex-page 's comment above. In general we should make links look like links and buttons look like buttons. I know there are some edge cases but with the introduction of an external link icon inside a button, that really starts to bring link functionality into a button and I believe that will add confusion rather than clarity.

Some follow up questions / thoughts:
- Where are they going when they click the actions? Is it another SFN tool/product?
- If the links are taking them to a completely different site or app, I would suggest trying to convey that through the link text if possible
