### ISSUE TITLE
[polaris.shopify.com] 404 not found at /foundations/foundations/designing-onboarding-flows

### ISSUE THREAD

**Issue by scott-radford** [Shopify/polaris-react-archive#6820]
"Designing Onboarding Flows"

Page is still showing up when I search, but then I get a 404 error.

**Comment by nblloyd** [comment]
@sradford6river Thank you for reporting this issue. Let me find someone that has some context on this, and I will get back to you.

**Comment by nblloyd** [comment]
Hi Scott. After digging into this a little bit, this page was intentionally removed because it wasn't touching on all the possible onboarding experiences. It was primarily focused on onboarding users when they install a new application. We did remove the bug that was still showing this page in search results, though, so you would no longer land on a 404 through that pathway.

Thanks again for reporting this!
