### ISSUE TITLE
[Icon]: Update Pin Icon

### ISSUE THREAD

**Issue by chrisblinstrub** [Shopify/polaris-react-archive#6844]
## Why are you proposing this update?

With the introduction of a new Pin icon as part of the [App Navigation project](https://vault.shopify.io/projects/18380), there's now inconsistency with two different pin icons used throughout the admin. The new pin icon being proposed will help create consistency across the admin, and also remove the need for a separate "unpinned" icon that I believe is currently not part of Polaris (more on that below). 

<img width="1428" alt="app-icon-comparison" src="https://user-images.githubusercontent.com/95929346/181793739-e20ce310-ab94-40bc-a4c8-784ae0d5b786.png">

## Icon name

Pin

## What type of icon set?

Both Major and Minor

## Icon SVG code

Pin Major SVG:
![PinMajor](https://user-images.githubusercontent.com/95929346/181790212-d7e067bb-4f70-47d3-abbf-fc1fb205d07e.svg)

Pin Minor SVG:
![PinMinor](https://user-images.githubusercontent.com/95929346/181790242-f63fd4cc-1c0f-4ab0-8ff3-2de9af7a75d1.svg)

## Are there any other important details?

- [Link to Figma file](https://www.figma.com/file/1lhdbPTTEXGm2LyatXQAQE/App-Launcher-%5BWorking-file%5D?node-id=5110%3A121811)
- The current Pin icon in Polaris is a "solid" style, while the new icon being proposed is an "outline" style. Typically the Pin icon is used in two different states (pinned and unpinned), so the proposed outline style will provide developers the flexibility to modify a few CSS properties to change the icon state without needing to swap out the entire icon. If you want to see this pinned/unpinned state change in action, you can [pin an app to your navigation](https://user-images.githubusercontent.com/95929346/182708131-f99973ed-14fb-40b5-a729-2851992a199f.png).

**Comment by yurm04** [comment]
> the proposed outline style will provide developers the flexibility to modify a few CSS properties to change the icon state without needing to swap out the entire icon.

I think this is possible if you're just embedding the SVG code/img. However, if you're using the Polaris `Icon` component it's not possible to modify the svg properties with css through the component API. I believe most of the admin is using the `Icon` component so i'm not sure this would address this use case

**Comment by yurm04** [comment]
Follow up! ☝️ the above is still relevant. Right now it's not possible to to change icon styling with CSS when you're using the Polaris [`Icon` component](https://polaris.shopify.com/components/icon). I had to do some digging because the `polaris-icons` package currently only contains the [filled pin icon](https://polaris.shopify.com/icons?icon=PinMajor&q=pin), and yet your screenshot of the `Reports` page contains an unfilled icon. This is because right now in shopify/web there is a custom, non-polaris icon that gets swapped out for the polaris pin icon when clicked. We would definitely much rather have this be an unfilled version of the pin icon provided by Polaris. Here's my recommendation to get what you need:

1. Open PRs to update the current Polaris `Pin` for major and minor icon to the new version you're proposing above. 
2. Open PRs to add new major and minor icons for the unfilled version of your new icon: `PinUnfilledMajor` and `PinUnfilledMinor` (feel free to call them whatever makes sense)
3. In Shopify web, open a PR to change the [`PinIcon` component](https://github.com/Shopify/web/blob/main/app/components/PinIcon/PinIcon.tsx) so that it's swapping between these new polaris pin icons.

You'll still need a filled and unfilled version of this new icon, but that's just a limitation of our `Icon` component right now, unfortunately. Let me know if you need help, happy to pair with you on this.

**Comment by chrisblinstrub** [comment]
Thanks again @yurm04 for looking into this further.

Before making any code changes, can I get a Polaris designer to review the new icons to confirm that these adhere to our icon standards? I've included in our [Figma file](https://www.figma.com/file/1lhdbPTTEXGm2LyatXQAQE/App-Launcher-%5BWorking-file%5D?node-id=5110%3A121811) both the updated `PinMajor` and `PinMinor` icons, as well as the new `PinUnfilledMajor` and `PinUnfilledMinor` icons.

<img width="592" alt="icons-preview" src="https://user-images.githubusercontent.com/95929346/182944906-4ecb590f-eadd-44d6-8de1-d98cc858453e.png">

**Comment by tracytees** [comment]
Looks good to me but perhaps @sarahill might have a different opinion?

**Comment by sarahill** [comment]
This looks great to me! @chrisblinstrub are you comfortable adding these to the [Polaris icons kit](https://www.figma.com/file/mMHFt3kEDNjLMZWowi6gnt/Polaris-Icons?node-id=753%3A2) too? I'm also happy to help with this :)

**Comment by heyjoethomas** [comment]
Hey @chrisblinstrub just wanted to check in on this issue. Everything looks great!

**Comment by chrisblinstrub** [comment]
Hey @heyjoethomas, just wanted to provide a quick update. 

I have a [PR](https://github.com/Shopify/polaris/pull/6978) set up to update the current `Pin` icon, and to add a new `PinUnfilled` icon. 

I've set it as a draft for now while our [Eng team makes updates](https://github.com/Shopify/core-workflows/issues/525) to the [`PinIcon` component](https://github.com/Shopify/web/tree/main/app/components/PinIcon), otherwise we would run into issues with users seeing our new Pin icon from Polaris, but still the old Unpinned icon that's not in Polaris. Once those changes are complete, I'll submit this PR for review. 

@sarahill not sure if the icons should be added to the Polaris icons kit now, or if we should wait until after the PR is complete, but any assistance you can provide on that when it's time would be much appreciated! :)

**Comment by thelemonyfresh** [comment]
Just noting explicitly that this is blocked by the above [core-issues ticket](https://github.com/Shopify/core-issues/issues/47737) being completed. 

Completion of this ticket should unblock https://github.com/Shopify/core-workflows/issues/526 for the wayfinding team.

**Comment by nickpresta** [comment]
Hi,

This issue has been kicking around for 6 months now without any progress so I want to propose a plan to move forward in a single place to bring visibility to all relevant folks. The first thing we should answer is **who is the champion of this change**?

Once we know who is pushing change forward, we should do the following:

1. Add the desired icons to Polaris ([PR in progress](https://github.com/Shopify/polaris/pull/6978)). This isn’t blocked by anything because it will be in a new Polaris version and won't automatically change anything in the Web Admin (`web`).
    - This step should be done by the person who is championing this change
1. When the new `polaris-icons` version is available and updated in `web`, update the [`<PinIcon />` component](https://github.com/Shopify/web/tree/main/app/components/PinIcon) to use the desired icons, and check both Reports Index and Metafields Definition Index to ensure the new icons look right, and adjust as needed.
    - The person championing this change should update `polaris-icon` in `web` and change the code to use these new icons.
    - The person championing this change should pull in someone from Optimize Analyze and Metafields team to verify their surfaces, if needed. 
    - This is basically what @yurm04 [proposed](https://github.com/Shopify/polaris/issues/6844#issuecomment-1204539675).
1. The [`AppTitleBar`'s `<PinIcon />`](https://github.com/Shopify/web/blob/b53b47da6e593ecf11ace821079d5a2ad28df29c/app/components/AppTitleBar/components/PinButton/icons/PinIcon.tsx) and the [`PlatformNavigationSection`'s `<PinIcon />`](https://github.com/Shopify/web/blob/aee9ac16414b96924b592acafd90c4c208089d3f/app/foundation/Frame/components/Nav/components/PlatformNavigationSection/components/NavItem/icons/PinIcon.tsx) should be changed to use the reusable [`<PinIcon />` component](https://github.com/Shopify/web/tree/main/app/components/PinIcon) that Reports and Metafields are already using (and have now been updated).
    - The teams who own the `AppTitleBar` and `PlatformNavigationSection` surfaces should switch to using the shared `<PinIcon />` component, making adjustments as needed.

---

It looks like the following still needs to be done (can check each item as completed and link to PRs):

- [ ] Merge in https://github.com/Shopify/polaris/pull/6978 (@chrisblinstrub created the PR, @Rmnlly has most recently changed it). This will satisfy Step 1.
- [ ] Update the [`<PinIcon />` component](https://github.com/Shopify/web/tree/main/app/components/PinIcon), which should include deleting the custom SVG and swapping the import of `EmptyPin` from that custom SVG to the new `PinUnfilled` icon from Polaris (e.g. 3 line change). Verify the change on the Reports Index and Metafields surface, pulling in those teams as needed. This will satisfy Step 2.
- [ ] Have the `AppTitleBar` and `PlatformNavigationSection` owners update to the shared [`<PinIcon />` component](https://github.com/Shopify/web/tree/main/app/components/PinIcon) or the Polaris `<Icon />` directly. I don't know who owns these surfaces, or how difficult it would be to swap, but I would expect the champion of this change to do some digging to find the appropriate team. This will satisfy Step 3.

**Comment by kyledurand** [comment]
Feel free to ping me for review once out of draft

**Comment by henryyi** [comment]
We also have a ticket that captures the required tasks and order to do them: Shopify/core-issues/issues/47737
