### ISSUE TITLE
[Icon]: New icon Filter (minor)

### ISSUE THREAD

**Issue by demipeppas** [Shopify/polaris-react-archive#6861]
### How will these icons be used?

In the Customer Segmentation Editor, clicking on the Filter icon opens a sheet that presents the Merchant with a variety of filters that they can use to segment their customers.

The current icon we're using is a placeholder, since there is no minor version of the Filter icon. This addition would be adding a Minor version to the Polaris icon library.

<img width="1229" alt="Screen Shot 2022-08-05 at 12 28 14 PM" src="https://user-images.githubusercontent.com/28149104/183120867-5b9a477b-eadb-49f2-ac28-b9f041cad5b7.png">

### Icon name

Filter

### What type of icon set?

Minor (16x16)

### Icon description

Used to represent an action to filter a list of items or resources.

### Icon keywords

filter, options

### Icon SVG code

```shell
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M2 6C2 5.44772 2.44772 5 3 5H17C17.5523 5 18 5.44772 18 6C18 6.55228 17.5523 7 17 7H3C2.44772 7 2 6.55228 2 6Z" fill="#5C5F62"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M5 10C5 9.44772 5.44772 9 6 9H14C14.5523 9 15 9.44772 15 10C15 10.5523 14.5523 11 14 11H6C5.44772 11 5 10.5523 5 10Z" fill="#5C5F62"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M7 14C7 13.4477 7.44772 13 8 13H12C12.5523 13 13 13.4477 13 14C13 14.5523 12.5523 15 12 15H8C7.44772 15 7 14.5523 7 14Z" fill="#5C5F62"/>
</svg>

```

**Comment by heyjoethomas** [comment]
Hey @demipeppas. Thanks for this work. Only thing I saw was the lines weren't ending on whole pixels. So I quick [redrew ](https://www.figma.com/file/HZoSikZUPBTCTzvjGPQXXu/Increase-UX-Quality-%F0%9F%92%AB%F0%9F%92%AB?node-id=6333%3A97940)with new strokes to make sure they snap to the pixel grid. I always recommend redrawing rather than scaling down a major to minor size to ensure everything is clean and crisp. 

This would then be ready for export and contribution to the Polaris React repo and moved into the Figma UI Kit. Docs on each of those processes is [here](https://polaris.shopify.com/contributing). Please reach out in the channel if you have questions or get stuck along the way. Happy to jump in and lend a hand.

**Comment by heyjoethomas** [comment]
Hey @demipeppas just wanted to check in on this. Are you planning on working on this? If so, feel free to assign yourself. Thanks so much.
