### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/modal)

### ISSUE THREAD

**Issue by curtisburns** [Shopify/polaris-react-archive#6950]
Is this no longer being deprecated? Just interested to know before I commit to using it throughout my app as I'd already started switching to app bridge's modal.

There was previously a warning in the documentation and wondered if it was just lost in the transition to the new site.

Thanks.

**Comment by chloerice** [comment]
Hey @curtisburns! 👋🏽 That's a great question.

Polaris stopped delegating rendering to App Bridge as of v5.0.0. The [two libraries can both be used together](https://shopify.dev/apps/tools/app-bridge/getting-started/using-react#using-app-bridge-react-with-polaris), but the removal of App Bridge from Polaris React changed the set up for embedded apps. So instead of wiring up your app to App Bridge through the Polaris `AppProvider`, it's done directly through the App Bridge React `Provider`. Components that render outside of the app frame, like `Toast`, `Modal`, and `ContextualSaveBar`, are provided by [App Bridge React](https://shopify.dev/apps/tools/app-bridge/actions/modal#react). It's essentially the same component, but the App Bridge React `Modal` handles the App Bridge delegation so you don't have to wire it up manually like you would have to with [the vanilla JavaScript modal action](https://shopify.dev/apps/tools/app-bridge/actions/modal#plain-javascript). 

With the [App Design Guidelines](https://shopify.dev/apps/design-guidelines) added to [shopify.dev](https://shopify.dev) in June, all app specific guidance and deprecation notices were removed from polaris.shopify.com so there'd be a single source of truth for apps.
