### ISSUE TITLE
Listbox flashes when open section in "More Filters" sidebar/mobile view

### ISSUE THREAD

**Issue by oksanashopify** [Shopify/polaris-react-archive#6970]
## Issue summary

I noticed that when we add [Autocomplete component](https://polaris.shopify.com/components/autocomplete) to the "More Filters" sidebar the options list flashes when we open it inside Collapsible section

Autocomplete component uses [Listbox](https://polaris.shopify.com/components/listbox) and [Combobox](https://polaris.shopify.com/components/combobox) components under the hood.
 Currently we can reproduce it on  Orders/Drafts --> "Customer" filter.

Video attached:

https://user-images.githubusercontent.com/104942025/184984519-97aef40b-b712-44ae-9fee-70d64234400c.mov

 
## Expected behavior
Options list should not flash when we open it inside Collapsible section

**Comment by chloerice** [comment]
Hey @oksanashopify 👋🏽 When you need to implement an autocomplete textfield inside of an overlay, like a modal or sheet, use the textfield and listbox components directly instead of the autocomplete or combobox components. Check out the [picker pattern documentation](https://polaris.shopify.com/patterns-legacy/pickers) for an overview of the searchable listbox composition and the [sheet](https://polaris.shopify.com/components/sheet) component's "With searchable listbox" example for a rough example of how to compose the listbox and textfield components.
