### ISSUE TITLE
'PolarisProvider' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by andershagbard** [Shopify/polaris-react-archive#6991]
Getting the following TypeScript error when using Polaris in a NextJS setup.

`'PolarisProvider' cannot be used as a JSX component.   Its instance type 'AppProvider' is not a valid JSX element.`

**Comment by kyledurand** [comment]
Do you have a link to your project @andershagbard ?

**Comment by andershagbard** [comment]
I just created this one: https://github.com/andershagbard/polaristest

Plain NextJS Typescript app with Polaris in the index.tsx file.

**Comment by kyledurand** [comment]
This seems like a compiler warning related to [swc](https://github.com/swc-project/swc) which next uses under the hood. 

I'll leave this issue open for another day because I could be wrong, and also to see if other people have run into this before and can chime in. Otherwise I think there are better places to look for solutions rather than at the Polaris level

Full error for searchability:

```tsx
'AppProvider' cannot be used as a JSX component.
  Its instance type 'AppProvider' is not a valid JSX element.
    Types of property 'refs' are incompatible.
      Type '{ [key: string]: import("/Users/kyledurand/polaris-test/node_modules/@shopify/polaris/node_modules/@types/react/index").ReactInstance; }' is not assignable to type '{ [key: string]: React.ReactInstance; }'.
        'string' index signatures are incompatible.
          Type 'import("/Users/kyledurand/polaris-test/node_modules/@shopify/polaris/node_modules/@types/react/index").ReactInstance' is not assignable to type 'React.ReactInstance'.
            Type 'Component<any, {}, any>' is not assignable to type 'ReactInstance'.
              Type 'import("/Users/kyledurand/polaris-test/node_modules/@shopify/polaris/node_modules/@types/react/index").Component<any, {}, any>' is not assignable to type 'React.Component<any, {}, any>'.
                The types returned by 'render()' are incompatible between these types.
                  Type 'import("/Users/kyledurand/polaris-test/node_modules/@shopify/polaris/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
                    Type '{}' is not assignable to type 'ReactNode'.ts(2786)

```

**Comment by BPScott** [comment]
I suspect this is due to having multiple conflicting versions of `@types/react` installed. `@types/react` v17 and v18 aren't compatible. Polaris switched to use * resolutions for these packages a while back in #5575. https://unpkg.com/browse/@shopify/polaris@10.0.0/package.json#L67


try deduplicating the dependencies on `@types/react` and `@types/react-dom` to ensure you've only got a single version of each.

**Comment by mandriv** [comment]
Had the same issue. This config resolves it:
```
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
```

**Comment by eatoncw** [comment]
I'm not totally sure why this started happening in my project (yesterday I did not see them), but was seeing the same error for every Polaris component (including Box for example) - adding those types @mandriv suggested silenced those ts errors.
