### ISSUE TITLE
[DRAFT] Proposed Updates to the Color Picker Component

### ISSUE THREAD

**Issue by theresa-paul** [Shopify/polaris-react-archive#7176]
## Color Picker
[Color Picker](https://polaris.shopify.com/components/color-picker)
_Note - this is a proposal to update the existing color picker to include Hex value input, and quick-select color swatches_ 

> The color picker is used to let merchants select a color visually. For example, merchants use the color picker to customize the accent color of the email templates for their shop.

### Examples
_No changes recommended to examples **with transparent value**, or **with transparent value, full width**, but we propose adding a new example, and updating **default**_

> ### Default
>
> Use when merchants need to select a color to offer them the choice between visually choosing from any color, or pasting pasting a hex value.
> <img width="202" alt="Screen Shot 2022-09-14 at 11 11 44 AM" src="https://user-images.githubusercontent.com/49034476/190198292-aa0cf3be-a107-4eb3-8470-8e456e0de13c.png">

> ### With Swatches
>
> Use when there is a list of relelvant options for merchants to choose from
> <img width="202" alt="Screen Shot 2022-09-14 at 11 11 44 AM" src="https://user-images.githubusercontent.com/49034476/190194722-46b70e28-26cf-4b40-9104-97aedc04085c.png">

## Props

List props and type declarations:

> - **onChange** (required): `(color: HSBAColor) => void` - Callback when color is selected
> - **color** (optional): `color` defaults to `false` – The currently selected color
> - **id?** (optional): `string` – ID for the element
> - **allowAlpha** (optional): `boolean` – Allow user to select an alpha value
> - **fullWidth?** (optional): `boolean`- Allow HuePicker to take the full width
> **Additional Props needed?? Will check with FED**

## Best practices

The Color Picker component should:

- Always provide swatches unless none are available
- Use the alpha slider if you want to allow merchants to be able to select a transparent color
- Position this component in the interface such that it maintains context to any previews which might demonstrate to the merchant how the color will be used.

**Comment by theresa-paul** [comment]
**Rationale:**
All of these proposed changes are to increase efficiency for merchants, and consistency across color-picking experiences in Shopify

**On the addition of the Hex value:** 
Almost all of the implementations of color picker across Shopify already include a hex-value input, but because the Polaris component does not include this variation, they are all slightly different. [see audit](https://www.figma.com/file/G8VvXDRjdnabf6q9eQ6YI3/All-the-Color-Pickers?node-id=0%3A1)

Hex values are consistently added to experiences despite it's ommision from the Polaris component because it is the most common way to choose colors consistently across the internet. It also makes copy-paste workflows across multiple buyer touchpoints more seamless for desktop-users. For these reasons, designers striving for [Familiarity](https://vault.shopify.io/pages/2250-Familiar) and [Efficiency](https://vault.shopify.io/pages/2248-Efficient) implement this feature in most of their color picker applications. 

On the addition of Swatches: 
The inclusion of handy-choices within reach increases efficiency for the merchant, and reduces cognitive load by forcing them to rely on memory. The square form factor min/maxes the surface area of the color for visibility, while keeping the component compact.

**Comment by kyledurand** [comment]
👋 Hey @theresa-paul. We had a similar [conversation in a PR recently](https://github.com/Shopify/polaris/pull/7041) about the addition of a tile / hex field being bundled with the color picker component and the overarching conversation led to something like: 

The Polaris team and library does not want to limit how consumers use our components. We don't want every iteration of the color picker to look exactly the same. Different parts of that admin require different solutions and consumers should be free to explore those solutions. 

Instead of implementing a solution in a pre-packaged, opinionated format, we added an [example](https://github.com/Shopify/polaris/pull/7141) of how consumers can achieve that layout and functionality without it being a direct part of our system.

Another reason we'd prefer not to lean too heavily into these kinds of opinions is that CSS is always changing and there are some exciting new [color functions coming soon to the web](https://www.smashingmagazine.com/2022/03/new-css-features-2022/#new-css-color-functions). We want Polaris to easily be able to accommodate new tech without having to ship breaking changes.

In a bright and hopefully near future we might have something in place where consumers can pick and choose composed implementations of Polaris components (i.e. many different types of color pickers with differing layouts). It's something we're thinking about.
