### ISSUE TITLE
Move Layout to Page subcomponent

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#7419]
With new layout components being introduced, the [Layout](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Layout/Layout.tsx) component becomes even more obscure. We could deprecate and remove it but it still serves a function and is widely used across the admin. 

I'm proposing we move it to the components folder within the Page component and expose it as `Page.Layout`. This would be a breaking change but a simple migration and I think it would also make its use case clearer

https://github.com/Shopify/polaris/issues/7419#tasklist-block-a205d510-1aec-4309-9c29-d3ca8486a3e2

**Comment by alex-page** [comment]
I would love to make migrations to replace the `Layout` component with the new combinations of patterns. Otherwise we are just keeping the component around because it is well used (I don't think that is a good reason).

**Comment by kyledurand** [comment]
I don't mind keeping it around, even if it is just the `Columns` component with opinionated spacing.

If we do remove it we'll see inconsistencies around annotated layouts and spacing between sections. Especially in 3p apps

**Comment by alex-page** [comment]
I see. A few thoughts.

1. The name `Layout` isn't useful long term so it would require an update
2. This is an opinionated layout and we are trying to have small un-opinionated primitives. This could cause confusion to developers on when to use what. How can we make this clear in documentation or guidance? If we make this clear is this a required component in the system or guidance?
3. Code is needed to scale this pattern but where should that code live? Close to primitives or elsewhere?
4. Could we make changes to the design of the admin that could allow us to use `Columns` without adjusting the spacing?

**Comment by SeanyB** [comment]
I'll share some of my thoughts too.

> 1. The name Layout isn't useful long term so it would require an update

I agree that his name is problematic because it's really a label better applied to a group of components.

> 2. This is an opinionated layout and we are trying to have small un-opinionated primitives. This could cause confusion to developers on when to use what. How can we make this clear in documentation or guidance? If we make this clear is this a required component in the system or guidance?

These are a really interesting and tough questions. 

From what I've seen doing 1P app reviews, the Page and Layout components are the opinionated components that are doing the heaviest lifting to keep the UIs at all consistent with other parts of the admin. There is just SO much wild UX design happening in our 1P apps. I worry about pulling these out of Polaris too soon, before we've had time to scale up Patterns, and we end up with even more variance in our 1P and 3P apps.

I'd prefer to make the first set of patterns *use* the Page and Layout components (or however it is renamed and packaged) in merchant-facing situations like settings pages, entity creation flows, onboarding, etc. The highest leverage value for our patterns will be helping designers/devs see how to build merchant experiences that aren't already individual components or documented yet.

**Comment by alex-page** [comment]
I agree with your take @SeanyB. Interested to figure out solving Page/Layout components in the future more holistically. Shouldn’t block the Layout project today.
