### ISSUE TITLE
[IndexTable] Sticky last column divider does not disappear when scrolling all the way to the right

### ISSUE THREAD

**Issue by LauraAubin** [Shopify/polaris-react-archive#7570]
## Issue summary

The sticky last column vertical dividing line on the IndexTable is not disappearing when scrolling all the way to the right side of the table.

## Expected behavior

Hide the sticky column when scrolling all the way to the right side of the table.

## Actual behavior

https://user-images.githubusercontent.com/22782157/198717382-919b27a1-63c8-4bfe-a7f8-7f9222961f16.mov

## Steps to reproduce the problem

1. Create an IndexTable with the prop `lastColumnSticky` with enough columns so that there is room to scroll.
2. Shrink the screen size until scrolling is available.
3. Scroll all the way to the right side.

**Comment by jesstelford** [comment]
Looks like this is fixed in the latest Polaris versions. [Sandbox link](https://polaris.shopify.com/sandbox?code=N4Igxg9gJgpiBcIAETIDsDOAXVBXbEAtjAE4ZIC8SA2gDpoorD2OMCWU8SA5AMwAsARkHcANC1ZJcJADZduAYjETWaAIbF5AWTVskAKRiE2GCGmUNJMiGDVY2Z%2BQBEYtrNNFIAqgGUAghaSSBAksGRcAEwADOKWrBoQuGhYPgAOMMnyACQRovxRUYGS2Hb48gDCJDB2MFBFrGAAFmpoaDByPAAKEGzJwQBmSD5qMjD1jKlqAJ7EyT5YpRjyAEow-UmwdbFB6zL9bDIysykL7ks8AGK4ewejWypIAL7bjMxx7Jw8EQCsAGwiL1Y0g6inGKHUmh4AFFDhkkAB5JoQNRgpDWNwONDyAAyEHIfjQAHN2jAMJ5fAFAYwQmFzrwYg8UAkkil0pkeFlBPlUSUzhUqjV7u8UE0Wm0QfC0DJejAhlgQmMqShJjMMidFvJOrohTtrvtDsd5hqeF40Lt9Xdxs8JABdADcEnQ2CQVVM0jAMAAchpZVQ3qwML1Cdc1CR5GB8PLiCRxqkZNIRuHI0RSBgio8HZYnThgBgSWAsLVVm6SB6yUgRjJi4lS6SfPnC1BPM00FBRvXRgXMeUW8THpQHvgYABJVswAAe1fdMCNhYAFBGCNGMABKTMiszOkgQADuOhIAGtcKlKHgl6mAHSENSpOcPO-CpD%2BoJIDhKxgQmDvlDouyY7-BKEqYAcycxslgAG8vgAGiq07QASqhqnNBjKMOatxIYs77Wo%2BvSwOOVIrpQAB8SAPkEAA8o74QAKmoABGowXssu6oSgHAUMAHCPGxSAHjAUycdxvF5p2jacaJriNlOtYYBevRgPGsAYHOHArjxj7KnibD2GYQljuOGlBMRvFUQZdGMTAF7lO0MgmZpjAUTRE44P0ZhYAA6jAbCEo0WAULQID0RAMhQIFFYYAFIAYJMaCBfZL6SMAn5GYlSAUQA9M545YAlL6ZdRE4WUxNmHHllGFeOxVWaVdnAL%2BuloI8BXmQxJW2eVkhmbRbU1R1vEoE5LkRVFMUtOFIw%2BWgxxRRkYXIGguDRmwYCdYlwA0qmqWJZl2W5aZGWVdV1n9Q53VFb1J1lQN6V7SNgVjXFyCTYS01qrNrbhYty2rTdTCgayarbflWUuWtjmHa1llXXZplHZdtXEbmyEYM1kM9dDiNw1D7VlcAsHimj8OY6dO3E7jdWIWqs74ETON9ddZ3kwzdXoQa1Mo3TGMU%2BDLXc1ZLE7p1K4vGu9ASFU7gkAw5GOdiMCEmoYBTOUoZQLzzO8a6NYet6xCcdr056zAwOsDpRjlIkyScYuUaXqMRJYI0puMJJBa1MOhaEBglsspxN2VjJZYdlJtRIAA-DwfiHNwSBcG70mkjrpIXg7hJO7xLsoGYIddmYPYtMSnEtm2M4Nt2vYm7xjTVFAQaRcAdAOUw9hYKM8jG9wOFpU%2BrftzwuIYmYXcAUwf0VtKr3HPIc2okEHDyJtJAALSQCyc%2BSH3MDyPCQEkKgVtYBvKDd2lz49y9b3stws%2Bjx88gA8vMVqsfjBb-IfiEIfSDP8kr%2Bn%2Btd%2BPAaZpgAS%2BYAQDuAFzgjIEeN0IE6X7twLUqo%2BhQVAXfBBbdt6XD1BhNUP8UZwIcjaLOaI1DYEtvGQgaB5grQPFMVC4MmDbj3KGI8qQXZ8wupZTqmV5aK2VqrUIeU1wgFECAJ2RhSQIGoCAX87cMggBtBIncHAnYYFkaQoAA)

![indextable-sticky-column](https://github.com/Shopify/polaris/assets/612020/7ccad18b-7a89-4cfa-9a2d-354ce7d2b147)

If you're still noticing issues, please feel free to reopen.
