### ISSUE TITLE
[Typography foundations] [Migration] Avatar

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#7582]
**[Figma](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/siMyneYEuULTaNSuRFZAcx/Polaris-Components?node-id=462%3A3886)**

Initials md: `heading-md`
Initials lg: `heading-xl`
Initials sm: `body-md`
Initials xs: `body-sm`

| Before | After |
|---|---|
| <img width="713" alt="image" src="https://user-images.githubusercontent.com/8629173/199076348-39a53185-cbee-4534-829c-9961a3b38996.png"> | <img width="754" alt="image" src="https://user-images.githubusercontent.com/8629173/199076163-7522f2cd-80ce-49b3-8dc3-9bee99dec267.png"> |
| <img width="293" alt="image" src="https://user-images.githubusercontent.com/8629173/199076447-72448f67-ca51-4456-a9d8-7502b7cccc69.png"> | <img width="291" alt="image" src="https://user-images.githubusercontent.com/8629173/199076228-86e8aa99-9fb4-44a5-8fe9-43c0cf43dfbe.png"> |

**Comment by laurkim** [comment]
The `Avatar` component is using the `svg <text>` [element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) not our `<Text />` component. We cannot pass it the `Text` component as a child because it only accepts specific [children](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg#usage_notes). Copying the styling from our Text variants results in visual regressions where the text becomes much smaller than the avatar. An example screenshot is provided below. Because of these issues, we've decided to leave Avatar as is without updates to typography.

<img width="360" alt="01-16-c10vn-rarby" src="https://user-images.githubusercontent.com/26749317/199316888-a1d1191e-493c-4d47-bd1e-f1895c914e46.png">
