### ISSUE TITLE
[Typography foundations] [Migration] Badge

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#7583]
[Figma file](https://www.figma.com/file/siMyneYEuULTaNSuRFZAcx/Type-migrations?node-id=367%3A343)
Both medium and small variants will now use `body-sm`

<img width="697" alt="image" src="https://user-images.githubusercontent.com/8629173/199086692-774396c2-1fe5-401e-8e6e-acd5ef97b973.png">

**Comment by laurkim** [comment]
@sarahill since the size prop only resized font-size, we should remove `size` as a prop on `Badge` in the existing branch for our next major release, since it's a breaking change. I was going to do it in the existing type migration PR, but I don't know the timeline for the release and don't want to block [the text migrations PR](https://github.com/Shopify/polaris/pull/7530).

[Commit](https://github.com/Shopify/polaris/pull/7530/commits/dd69c56a26cdd15e9b7c2b049481df2dc24e5464) with update.
