### ISSUE TITLE
TextField `max` prop does not limit user input

### ISSUE THREAD

**Issue by dhmacs** [Shopify/polaris-react-archive#76]
# Issue summary

The `TextField` component has a `max` prop to limit input for numeric (and date-time) inputs, but that prop is only used to limit the increment done by clicking on the arrows, and not to limit values typed from keyboard or pasted.

## Expected behavior

When `max` prop of `TextField` is set, the textfield should never contain values greater than max.

## Actual behavior

Even if `max` prop is set, the user is allowed to type or paste values greater than max.

## Steps to Reproduce the Problem

1. 
```
<TextField
  label="Quantity"
  type="number"
  value=""
  max="4"
/>
```
2. Type from the keyboard or paste inputs greater than `max` prop

## Specifications

- Polaris version: 1.0.3
- React version: 15.4.2
- Browser: 58.0.3029.110 (64-bit)
- Device: MacBook Pro
- Operating System: macOS Sierra

**Comment by lemonmade** [comment]
Hey @macs91. This is a tricky one. We are really just shelling out to the native HTML input behaviour of `max`/ `min`, which do not actually restrict the value from going over that amount. We could conceivably force this behaviour with numbers (although it's tough to decide what the correct behaviour should be in all cases — outside the boundaries, things that aren't numbers, a blank value, etc), but it would be extremely hard to enforce on dates given that we would need to parse and evaluate the provided date against the limits (which gets in to a whole separate discussion about internationalization). My feeling is that this is probably better accomplished by the consumer of `TextField` when handling a change in value, rather than us trying to make that decision in the component itself.

**Comment by macs91** [comment]
@lemonmade I see what you mean if your goal is to mimic the native HTML input behaviour.. Then I may suggest to update the doc to point this out, since after reading the doc, I was expecting the behaviour I've described. 

Thanks for the clarification!
