### ISSUE TITLE
Data visualisations correctly show gaps with time between them

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7610]
With the outcome of https://github.com/Shopify/polaris/issues/7512 we will need to make sure the visualisations still look accurate despite having different daily gaps.

**Comment by sam-b-rose** [comment]
We implemented a strategy of only splitting the data between historical and latest. We won't need to address adjusting visuals since there aren't gaps in the data.

**Comment by aaronccasanova** [comment]
@samrose3 I think there are still date gaps in our data regardless of the recent historical/latest updates we introduced. Currently, the `--days` option in our CLI maps to the `git log --since="..."` option and daily commits are not guaranteed. Take for example this log of Polaris commits from the last 5 days:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/32409546/206887624-98afd917-7a70-4e59-bfb5-04fe5c8ee651.png">

I assumed this issue was addressing the fact that `2022-12-08` wouldn't have a data entry and could show a gap or incorrect visualization on the site. cc @alex-page Can you confirm that assumption?
