### ISSUE TITLE
User input labels have inconsistent naming, causing problems when changing state variants

### ISSUE THREAD

**Issue by idonahue** [Shopify/polaris-react-archive#7795]
## Issue summary
When a designer is using an text input component and swaps state from `Placeholder` to `Filled` they have inconsistent name of layers (some times "Input", "Label", "Placeholder text"). This causes unexpected behavior as a designer.

## Expected behavior
When using Text input and swapping, I expect all text input components to swap with out text changing unexpectedly 

## Actual behavior
When using Text Input and swapping from different versions and states, it doesn't swap consistently and text changes

**Comment by idonahue** [comment]
Realizing that this will break existing Figma projects when Figma files are updated. 

Why will it break things? If using an input text component, when updated it will be changing layer names and potentially the content (text) of those layers.

Now sure how to proceed.

**Comment by heyjoethomas** [comment]
Hey @idonahue thanks for posting. Yeah the labels are there to help clearly identify the state and since the wouldn't stay the same in production, since the user has input something into the field, not if one way is clearly better. 

As you stated, this change would be a large breaking change so gonna leave it alone for now. We are talking about what we can do in 2023 to improve the UI Kit though so I will leave this open for a reference in that discussion.
