### ISSUE TITLE
Is Tabs supposed to have an id property?

### ISSUE THREAD

**Issue by buggy** [Shopify/polaris-react-archive#79]
# Issue summary

I have a `<Tabs>` with number of `<Tabs.panel>` as the children.

`<Tabs.panel>` requires `id` and `tabID`. From https://github.com/Shopify/polaris/issues/62 I understand that `id` of the `<Tabs.panel>` should match the `panelID` from `<Tabs>`.

What is `tabID`? It's required and I assume it should be the `id` for the related `<Tabs>` but that component doesn't accept an `id` property.

## Specifications

- Polaris version: 1.0.3
- React version: 15.5.3
- Browser: N/A
- Device: N/A
- Operating System: N/A
- TypeScript 2.3

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
Hey Rich, we definitely need to work on the documentation for Tabs. The ID property that is referred to here is the one you are required to supply with each of the tab descriptors you pass to `Tabs` (each object in the array you pass for the `tabs` prop). So, we would expect something like this:

```ts
<Tabs
  tabs={[
    {title: 'First tab', id: 'tab-1', panelID: 'panel-1'},
  ]}
/>
<Tabs.panel id="panel-1" tabID="tab-1">
  Panel contents
</Tabs.panel>
```

This associated the two together via aria attributes.

(by the way, we have a change coming in our next release to fix `Tabs.panel` -> `Tabs.Panel`. It won't be a major release because I consider it a bug fix, so make sure to update the casing when you update to the next version)
