### ISSUE TITLE
Date picking - minor prototype tweaks

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7930]
[Figma design](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4822%3A219513)

- [x] Update subheading under **Date picking** title to: `Lets merchants select a date or date range to help them filter information or objects and schedule events or actions.` 
- [x] Update copy of **How it helps merchants**, point 2 to:`A single month calendar allows merchants to select a date while seeing its relationship to other days.` 

- [x] Update 3rd **Useful to know** image asset for the **Date list** pattern to match this one in Figma.

![Image](https://user-images.githubusercontent.com/421723/212772876-c3694711-1c6d-402d-8b0a-b23e14a2b737.png)

- [x] Ensure the **How it helps** image asset used for the **Date range** pattern has the label `[Done]` instead of `[Apply]`.
    - This is to match Polaris content guidelines.

![Image](https://user-images.githubusercontent.com/421723/212752173-b7f326ca-d6bb-4509-9293-de614a435908.png)

- ~[ ] Update the **Related resources** links to match [Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=3676%3A167709&t=Wfh8XdUzAQkojg9N-1).~
    - ~This assumes that the work to switch them to a list of links in #8057 is already complete.~
    - _Will be completed as part of #8057_

**Comment by jesstelford** [comment]
This is now deployed to staging.

Feel free to close the issue if it all looks good 👍

**Comment by SeanyB** [comment]
Thanks, @jesstelford. 

However, the last item - to replace the image with the one from Figma that looks similar to the one attached to the issue above, isn't complete. We need to use an image with a date list rather than a calendar in that one.

**Comment by SeanyB** [comment]
I've updated this issue with the latest adjustments.

**Comment by johanstromqvist** [comment]
> Remove periods from all single sentence numbered items in How it helps merchants. This follows [punctuation for lists](https://polaris.shopify.com/content/grammar-and-mechanics#punctuation) guidelines in Polaris.

The guidelines suggest to use punctuation when "any list item contains two or more sentences". I think we should consider these annotations as paragraphs and keep punctuation consistent across all pattern detail pages. cc: @selenehinkley (not sure who added the task) The alternative is to mix punctuation styles in the same element type, and make sure that authors follow suit.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/38329124/212755228-96bb0142-7dc6-4b8d-90df-4b77ca1a5b6f.png">

**Comment by SeanyB** [comment]
Good point, @johanstromqvist. Mixing the punctuation inside one list would be confusing. Let's do as you suggest. I will remove that task from this issue.

**Comment by selenehinkley** [comment]
Yep, that's correct. So how it works is if you have one bulleted list with single sentences, you don't use punctuation. If you have another bulleted list (on the same page) and it has more than one sentence per bullet, you add punctuation. Example: 

- lalala
- lalala
- lalala

---

- lalala. lalala.
- lalala. lalala.

I added that point because I saw periods for all list items and it breaks from the pattern we follow.

**Comment by johanstromqvist** [comment]
My suggestion is that we would prioritize consistency **_across_** pages.

| Pattern 1 | Pattern 2 | Pattern 3 |
| ----- | ----- | ----- |
| - lalala. lalala. | - lalala. | - lalala. lalala. |

In other words, annotation in "How it helps merchants" always use punctuation because many annotations across pages do. If one pattern page happens to have 3 annotations that are all single sentence, they should still use punctuation.

**Comment by jesstelford** [comment]
Added punctuation as a decision to the Vault project :+1:

**Comment by jesstelford** [comment]
@SeanyB I've updated the two images outstanding. They've been pushed to our working branch, and they'll go out with the next staging deploy.

The last point about Related Resources I've struck through since @gwyneplaine is going to handle that as part of #8057

**Comment by johanstromqvist** [comment]
> Added punctuation as a decision to the Vault project 👍

Thanks @jesstelford! I updated it to concern the annotations in "How it helps merchants" specifically, because it often has multi-sentence paragraphs.

"Related resources" are almost always single-sentence (or should be) so they can still leave out punctuation according to the Polaris guideline.

**Comment by johanstromqvist** [comment]
Looks great – thanks! 🔥

Checked the following:
- [x] Update subheading under **Date picking** title
- [x] Update copy of **How it helps merchants**, point 2
- [x] Update 3rd **Useful to know** image asset for the **Date list** pattern to match this one in Figma.
- [x] Ensure the **How it helps** image asset used for the **Date range** pattern has the label `[Done]` instead of `[Apply]`.
