### ISSUE TITLE
App settings layout - minor prototype tweaks

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7938]
**NOTE:** This issue is dependant on the outcome of the code compositions decision in #7961.

[Figma](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4822%3A219177&t=Wfh8XdUzAQkojg9N-1)

**Pattern page:**
- [x] Rename the title from `App settings` to `App settings layout`.
- [x] Update the second **Useful to know** image to one that doesn't have the unnecessary purple line in it.
- [x] Adjust the page width to match other pages in Polaris site.
    - This should be accomplished in #7994.

**Composition code:**

This is the code composition we're providing to all admin builders. We're transitioning to build quality, so please review the code and layout for quality and desired behaviour within the context of this github issue. Below are some issues we have noticed so far:

- [x] Add appropriate padding to the left and right of the text at breakpoints smaller than `--p-breakpoints-sm`.
- [x] Remove padding and rounding of cards when smaller than `--p-breakpoints-sm`.
- [x] Layout should be centered on the larger breakpoints.
- [x] Fix the indentation in the code sample. 
    - The indentation inside the Page component is too large.

Current pattern composition code:

![Image](https://user-images.githubusercontent.com/421723/212760735-9c5f0371-a115-4078-8e39-94d41e7c1ff8.png)

Annotated Layout component examples:

![Image](https://user-images.githubusercontent.com/421723/212761168-2f9aad20-c435-487f-8f84-ba23f82a047a.png)

![Image](https://user-images.githubusercontent.com/421723/212761208-61c6d5c7-629d-4bdb-893a-7f3be91adbed.png)

**Comment by gwyneplaine** [comment]
Is this how tablet view should look?  
<img width="844" alt="Screenshot 2023-01-18 at 3 58 03 pm" src="https://user-images.githubusercontent.com/12119389/213087925-b7d4c8dc-3369-4f5c-a7c0-5149de4028b3.png">

At the moment (likely due to the re-addition of the TOC) the example width on the pattern page is an awkward 758px (just below small desktop screen size), so we get this awkward large tablet look.  Silver lining is that we get to interrogate whether or not large tablet experiences are adequate. 

@SeanyB  @jesstelford  there's a tangential issue here we need to discuss around the width at which examples are displayed on the page, now that the TOC has been added back in.

**Comment by johanstromqvist** [comment]
The whole pattern page is focused on a two column layout, which makes defaulting to a single-column tablet width in the preview problematic. It reveals a bigger root problem which is our general desktop-first focus in both product and product documentation. That root problem is too big for us to solve right now, so I'm wondering if there's a way to show a small desktop view despite the lack of available width.

- Could we perhaps adjust the scale in the iframe?
- Or potentially have a fixed width inside the frame and have overflow-x scrollable?

Not sure how it would affect DX, but could be worth looking into if the fixes are feasible.

Pinging @martenbjork because this topic may have been considered in the component previews.

**Comment by jesstelford** [comment]
The example rendering width is a problem I've detailed in https://github.com/Shopify/polaris/issues/7966 - the decision was made to leave it as-is and only render the tablet view.

Might be best to move the discussion over there 👍

**Comment by johanstromqvist** [comment]
Checked the following. Looks great! Thanks friends ✨

**Pattern page:**
- [x] Rename the title from `App settings` to `App settings layout`.
- [x] Update the second **Useful to know** image to one that doesn't have the unnecessary purple line in it.
- [x] Adjust the page width to match other pages in Polaris site.

**Composition code:**
- [x] Add appropriate padding to the left and right of the text at breakpoints smaller than `--p-breakpoints-sm`.
- [x] Remove padding and rounding of cards when smaller than `--p-breakpoints-sm`.
- [x] Layout should be centered on the larger breakpoints.
- [x] Fix the indentation in the code sample.
