### ISSUE TITLE
Create code examples: Resource index layout

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7943]
- Pick up the work when components have been upstreamed to Polaris react
- Guide builders how to make important layout-related design decisions that output the pattern
  - As per [this list](https://github.com/Shopify/polaris/issues/7943#issuecomment-1450654431)

**Comment by johanstromqvist** [comment]
See [#7931](https://github.com/Shopify/polaris/issues/7931) for design and content for the Resource index layout pattern.

**Comment by johanstromqvist** [comment]
@jesstelford & @gwyneplaine What's the state of the code example? Are we completely blocked until the filter tabs are upstreamed, or is there anything we can do proactively?

**Comment by jesstelford** [comment]
😅 My first thought is: Holy crap, that's complex!

Assuming this is the thing we're trying to build:

![image](https://user-images.githubusercontent.com/612020/221447607-fca2994f-f272-4463-ba6a-d4570a047324.png)

It rapidly blows past the realm of "copy+pastable code" due to all the logic requirements:

_Edit_: After speaking with @alex-page, I now understand that this is a composition of [`Filters`](https://polaris.shopify.com/components/selection-and-input/filters), [`IndexTable`](https://polaris.shopify.com/components/tables/index-table), and [`ChoiceList`](https://polaris.shopify.com/components/selection-and-input/choice-list) components. There is a team who are working to update each of these which will be contributed back upstream to Polaris. Even with this new information, there still stands quite a lot of questions (old questions are struck through):

1. The data has to be in a form that can be filtered and sorted, probably a huge JSON object.
1. All / Active / Draft / Archived filters requires / implies every item needs its own state, and a unique pill for display
1. The + implies there's some form of interaction there? Does that open a modal? Go to a new screen? Insert a new dummy row? Do nothing?
1. The up/down arrows do... something. What? Change the sort direction? Does that mean it needs to know which is the currently sorted column?
1. Are there empty states (eg; for "no search results", or even generic "nothing to display")?
1. Does selecting an item change how it looks in the table?
1. "Product" appears sortable, but not the other columns? Is there a reason behind this / what's the logic to determine what's sortable and what's not? Are multiple columns sortable at once? Eg; Sort by state ("Active" first), then by inventory (ascending), then alphabetical to get a list of all your low stock items)
1. Where do the product thumbnails come from?
1. Not pictured are 'Export', 'Import', 'Add Product' buttons. What do they do? Open modals? Nothing?
1. What's the mobile breakpoint meant to look like? Is it horizontally scrollable?
1. ~~Search button on the right implies some kind of search input. How is that meant to work? Is it a fuzzy search? Search titles only? What does it look like? A modal? What do the results look like? A filtered list, or are results highlighted somehow?~~
1. ~~The "select all" checkbox has some kind of selection behaviour, what is it? What happens when you already have some items checked, does it just check all anyway? Confirmation first? Unchecks them on first click? What happens if you check all items? Does the "select all" go into the "checked" state? What happens when you select _some_ items? Does the "select all" go into the partially-selected state? What happens when you click "select all" after they're all selected?~~

We can definitely give this a crack, but it's an entire project in itself that could take weeks to build right, which I think falls well outside the scope of our Patterns work. Hopefully there's some existing code we can leverage somewhere?

_Edit_: After the conversation with @alex-page, my suggestion is to wait until the upstream changes are contributed back to Polaris, then we have another look at this. I have a feeling it'll be too big of an example to be usefully copy+pasted and instead will need some kind of long-form content to describe how all the pieces work together.

**Comment by SeanyB** [comment]
> 😅 My first thought is: Holy crap, that's complex!

I agree, @jesstelford. I think we've veered into too much detail here and away from the goal of a common page layout for resource details.

Here's what I think this needs:
1. Page action buttons
    - Add product primary action button
    - Export and Import secondary action buttons
    - In all cases, these buttons don't do anything. They are communicating layout only.
2. IndexTable with columns for Product, Status, Inventory, Type, and Price.
    - The up/down arrows should come with the IndexTable component - if not, lets reconsider. They should be enabled for all headings except Status, but they don't need to actually sort the list.
3. Five rows in the index table that are generic.
    - The content can be the same in every row if making them different causes the example code to be harder to understand.
    - The same empty state image should be used for all of the products.
    - For the Price, be sure to right-align the text to reinforce that numerical columns should be right-aligned.
 ![Image](https://user-images.githubusercontent.com/421723/222229129-2115c6f2-744a-404f-84c7-7278645cb2d6.png)
4. IndexFilter at the top with All, Active, Draft, and Archive items.
    - I should not actually function. It's more about representative placement than building the full functionality.

**Comment by jesstelford** [comment]
Those simplifications greatly reduce the complexity! Thank you.

It makes me wonder if we can do a similar set of simplifications for the Date Range component? There's a bunch of complex code in date range to get it wired up and working correctly, which might imply to a builder that code snippets on Patterns are fully functional, but that expectation would be broken when coming to the Resource index layout page where only the layout code exists 🤔

**Comment by SeanyB** [comment]
> It makes me wonder if we can do a similar set of simplifications for the Date Range component? 

I believe the best path forward for the Date Range pattern is that its provided as a more fully functional component.

**Comment by johanstromqvist** [comment]
Decisions (updated first comment)
- Pick up the work when components have been upstreamed to Polaris react
- Guide builders how to make important layout-related design decisions that output the pattern
  - As per [this list](https://github.com/Shopify/polaris/issues/7943#issuecomment-1450654431)

**Comment by SeanyB** [comment]
Done! 🎉
