### ISSUE TITLE
Pattern detail page - Variant tabs

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#8055]
**Variant tabs:**
- [x] Add negative `16px` negative margin to the left and right of the tab 'box'. [Figma option 2](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4622%3A191580&t=Wfh8XdUzAQkojg9N-1)
    - Note that this should align the left content _inside_ the tab with the left content of the rest of the page.
    - If this would incur undue technical debt/complexity, we can keep [option 1](https://www.figma.com/file/JUKo15oKz1aCcdeNP4UxyE/Reboot-Polaris-Patterns?node-id=4622%3A191116&t=Wfh8XdUzAQkojg9N-1) (current staging).
    - UX Reasons for preferring **option 2**:
        - Content alignment is always the same across variant and non-variant patterns.
        - We don't pay any padding cost from the tabs on the content inside them.
- [x]  Remove "pressed" state of tabs, so they only have a hover state (dark grey) and an active state (light grey) when the tabs are selected. 
- [x] `Shift_tab` should scroll the tab control on-screen when focus is returned to it. It's currently hidden behind the page's titlebar.

**Comment by jesstelford** [comment]
> Remove "pressed" state of tabs, so they only have a hover state (dark grey) and an active state (light grey) when the tabs are selected.

Pressed _is_ active. No way to remove one without removing the other.

The issue comes because clicking the tab title is clicking a button, and that button is receiving focus. When it has focus, it's "active", and it retains that focus once the click is finished (ie; normal button behaviour).

We could change this behaviour to move the focus to the new tab content once it's loaded, but that has accessibility concerns;

- What element do we focus? The first focusable element might be _past_ the initial content, so screen readers will miss that content.
- If we focus the enclosing `<div>`, I believe some screen readers behave oddly (because it's not normally a "focusable" element)
- If we remove focus entirely, we're essentially resetting the screen reader back to the top of the page.

I've seen all 3 options above implemented in various states, but am not well enough versed in a11y to know what's best beyond the current implementation of "Don't mess with the defaults".

**Comment by gwyneplaine** [comment]
Resolved and pushed to #7843   
![18-55-percu-fpujj](https://user-images.githubusercontent.com/12119389/213038591-0749f03b-9cc5-4092-9cb1-1676aba2b9a0.gif)

**Comment by johanstromqvist** [comment]
Looks great based on video – thanks!

- Any concerns regarding the negative margin?
- Any outstanding a11y concerns regarding focus?

Not sure what our process is but I'll close this and mark it as done.
