### ISSUE TITLE
Plan a user testing session

### ISSUE THREAD

**Issue by tracytees** [Shopify/polaris-react-archive#8068]
### Goals of user testing of pattern reboot:

- To uncover users expectations when interacting with the new pattern page redesign
- To optimize the information shown so it is easy to understand and absorb

Once the pattern reboot is in a good place, user testing would be helpful in informing us on how to improve it further. 
A [document](https://docs.google.com/document/d/1xEJXnr4P8BF3u8bQ-Gc9hy8GpDsUCRN-XQ0EXC-0b9Y/edit?usp=sharing) has already been started with come questions and base information. Feel free to change and use it when there is time for user testing.

**Comment by johanstromqvist** [comment]
Thanks for taking this initiative, Tracy! On a related topic, I've been wanting to give analytics a think too, but haven't come around doing it. Do you have any thoughts on what data we might be able to track on the site and what insight we might be able pull from it?

**Comment by tracytees** [comment]
Here are the following things that might be helpful to track:
- tab clicks (to see whether it's the correct interaction to keep using in the future)
- Redirects from component tags (to see if our hypothesis of connecting components to pattern worked)
- Sandbox interaction — edit sandbox or general interaction with sandbox 
- Page scrolling data vs clicking on right nav (to find out if there's a trend of what users might be wanting to know about most)

Let me know your thoughts!

**Comment by nblloyd** [comment]
@tracytees Can we start planning this now? We have a pretty functional staging environment that could be used for testing purposes. Would be great to get user input ASAP so we can implement the highest priority feedback before shipping.

(cc: @bernardojoaogarcia since we talked about this in our one-on-one last week)

**Comment by johanstromqvist** [comment]
Note to self: consider planning this issue together with #8050 and potentially schedule another user testing session post-launch

**Comment by SeanyB** [comment]
We should seek input on how developers would like the code examples to help them learn how to use them. This relates to this issue: https://github.com/Shopify/polaris/issues/8177

**Comment by SeanyB** [comment]
I've added [candidate 1P apps](https://docs.google.com/document/d/1xEJXnr4P8BF3u8bQ-Gc9hy8GpDsUCRN-XQ0EXC-0b9Y/edit#) and the respective UX and Eng owners to contact for getting feedback on the App Settings layout pattern. I've included some additional notes on each one so that you have context on their apps when reaching out. I've personally met with each of these folks to discuss the ADG feedback before. For some of them, be sensitive that we've recently asked them to make a bunch of UI improvements to meet the ADG. They should know we're asking for feedback on our pattern, rather than directing them to make a bunch of new UI changes.

**Comment by tracytees** [comment]
Minor concerns brought up in the user testing that we might want to address:

1. A few developers didn't notice the show code feature in the page...Suggested to perhaps have it shown automatically instead of needing to click
2. The playroom render looked like a repeated static visual on the page.
3. Posed a question of copying all the code and its length. Is this feasible and expected of builders? - (regarding the date range variant)
4. In the playroom the pattern reduces to a mobile breakpoint when the ToC is displayed on a 14" screen.
5. When clicking on tabs, it would be ideal if the page didn't jump back to the top
6. Component tag didn't look immediately clickable

**Comment by SeanyB** [comment]
Thank you, @tracytees!

>1. A few developers didn't notice the show code feature in the page...Suggested to perhaps have it shown automatically instead of needing to click.

Implementing [this Github issue](https://github.com/Shopify/polaris/issues/8052) should resolve this.

> 4. In the playroom the pattern reduces to a mobile breakpoint when the ToC is displayed on a 14" screen.

Agreed on this issue and it will be fixed in [this issue](https://github.com/Shopify/polaris/issues/8248#issuecomment-1416389145).

> 5. When clicking on tabs, it would be ideal if the page didn't jump back to the top

I’ve created #8322 to track a fix.


> 2. The playroom render looked like a repeated static visual on the page.
> 3. Posed a question of copying all the code and its length. Is this feasible and expected of builders? - (regarding the date range variant)
> 6. Component tag didn't look immediately clickable

The other issues are interesting and we should keep an eye on them, but I don’t think we need to make any additional changes before publishing.
