### ISSUE TITLE
Sandbox (Playroom) editor is unintuitive on first use

### ISSUE THREAD

**Issue by jesstelford** [Shopify/polaris-react-archive#8175]
Based on feedback & usage observations, we could improve documentation/implenentation on the following:

- How components are rendered
- The fact only a single component is rendered
- The fact blank lines are important
- The available imports
- How to include state mangement
- Does it even support raw JS? (yes)
- How are errors reported?
- What's the difference between a locale and a theme?

**Comment by johanstromqvist** [comment]
Thanks Jess! Yeah, the sandbox hasn't gotten much love recently, has it?

What's you preferred approach?

My hot take is that we should
1. address any must-haves and low hanging fruit pre launch
2. include the sandbox in end-to-end user testing (#8068) as a fast follow

That would allow us to ship v1 as planned and provide value sooner, then make an intentional list of prioritized improvements and dedicate time to fix them. In the list above, are there any problems that seem critical and/or might have easy high value fixes?
