### ISSUE TITLE
How might we document the code in the examples for each variant?

### ISSUE THREAD

**Issue by jesstelford** [Shopify/polaris-react-archive#8177]
The UX documentation for each pattern is thorough and succinct. The code examples, however, have little to no documentation.

How might we provide as much clarity about the structure of the code as we do the UX?

**Comment by johanstromqvist** [comment]
Great call!

Two Qs:
1. Does "document the code" mean "adding comments to the code", or are there other opportunities and good practices we could use?
2. Is there a documentation need in _variants_ specifically, or is this a general question for all code examples?

Thoughts regarding code comments in general
- While we want to keep guidance on the page succinct, we could be generous with comments in the code
- Make sure there's parity between "Useful to know" guidance and code comments, e.g. "Remove the `fullWidth` prop if the index columns don't use the space" (adding this to the design tasks in #7944 and #7943 )
- Check if there are other places in the code where builders make decision that might require some guidance
- Leave comments where there's a high risk that pattern-breaking changes could be made

**Comment by SeanyB** [comment]
We have some prior art in [Shopify.dev](https://shopify.dev/apps/getting-started/build-app-example/frontend) on documenting code examples.

**Comment by johanstromqvist** [comment]
Help me wrap my head around the need here please. What might documenting code look like in patterns? What sort of documentation do builders need? Are we talking about new content on each pattern page?

**Comment by gwyneplaine** [comment]
Here's a rough starting prototype of what this could potentially look like in the future. 

-------

**DISCLAIMER**
All of the content in the links below are **very** WIP and serve only to illustrate the wider point around longform content to service better code documentation for patterns. Please don't assume this is completed content, or that this is set in stone. 

-------

As per @jesstelford's excellent video, we've created two examples of pattern code documentation: 

* [One is forward facing](https://github.com/Shopify/polaris/blob/a0b7be10f0349e26622bb57053ef4d156971fbd6/polaris.shopify.com/content/patterns/app-settings-layout-code.md), where we require the user to build the pattern from Polaris primitives. 
* [The other](https://github.com/Shopify/polaris/blob/a0b7be10f0349e26622bb57053ef4d156971fbd6/polaris.shopify.com/content/patterns/date-picking-code.md) is backwards facing (where we have a installable package that gets them all/most of the way there). 

Main takeaways of this exploration so far: 

### Changes
* The intention is for the above two markdown links, to be in a **new tab** next to the existing pattern guidance (principles). We think this is best, since while the code documentation will want to reference the pattern principles on the UX guidance tab, the opposite is likely untrue. (UX builders probably won't always find implementation detail and code documentation relevant) 
* Crucially this means no code example on the UX guidance tab.
* We also think the variants should now have their own pages, a la component groups.

### What we want the code documentation to include

- Learning the pattern
  - What's important when implementing this pattern
  - Why's the pattern important
  - When should we use this pattern?
- Principle first, then extrapolate/explain technical decisions from there.

### What we don't want the code documentation to include

- Teaching Javascript
- Teaching Polaris
- Teaching React

### Dependencies

- We'll likely want to work with technical writers to create this content, its a lot of content that engineers by themselves probably won't have the space or time to do well. 

### Learnings:

- **There's no one size fit all solution for this**, previously we assumed structured content was the natural evolution of patterns. Briefly exploring pattern code documentation has led us to believe the opposite. Each pattern is different, and therefore the documentation required to service the pattern will inevitably also be different. 
- The Challenge is how we make this workload manageable for
  a) the team
  b) future contributors

**Comment by yurm04** [comment]
@gwyneplaine  I like the direction this is going in and encourage us to start prototyping with this is mind! Some additional thoughts:
* A UX tab and a Dev tab makes sense in order to give each audience the space they need. But what about the overlap where things may not be strictly UX or strictly dev focused? What information is critical for any audience to have and how do we make sure that doesn't get lost?
* Related to above: how can we make sure that we are still bridging the gap between designers and developers even as we explore ways to provide dedicated spaces and information for each audience? 
* Can we provide additional tooling that helps to draw clearer connecting lines between UX space and Dev space? ex. figma plugins and VS code extensions? what about new treatments of the information we provide?
* What would it look like if we don't separate the UX and the dev, but find a (new) way to overlap the information together. Ex. a toggle that changes code specific comments to UX redline comments? Different information, same visual treatment. Just a thought to try and make the connection between UX and dev work closer

**Comment by gwyneplaine** [comment]
For sure @yurm04! I'm keen to jam and work this out together as we progress. Some Initial thoughts: 

> * A UX tab and a Dev tab makes sense in order to give each audience the space they need. But what about the overlap where things may not be strictly UX or strictly dev focused? What information is critical for any audience to have and how do we make sure that doesn't get lost?
> * Related to above: how can we make sure that we are still bridging the gap between designers and developers even as we explore ways to provide dedicated spaces and information for each audience?

- I think we shouldn't be afraid of repeated content. Some things are worth saying more than once, and I get the feeling that the principles we've currently defined and placed under `UX Guidance` are one of those things. 
- In addition to the above layout and infrastructure is one way to bridge the gap mentioned above (which I'm excited to experiment with). That said its worthwhile calling out that I'm also interested in how the content itself could be leveraged to do this, links in between relevant content blocks and  or repeating content in different ways to speak to different audiences is one example that I'm curious to explore. 

> * Can we provide additional tooling that helps to draw clearer connecting lines between UX space and Dev space? ex. figma plugins and VS code extensions? what about new treatments of the information we provide?

- I don't yet know what this would look like, but I'm very excited by the possibility of bringing docs closer to our tools +11111 


> * What would it look like if we don't separate the UX and the dev, but find a (new) way to overlap the information together. Ex. a toggle that changes code specific comments to UX redline comments? Different information, same visual treatment. Just a thought to try and make the connection between UX and dev work closer

- cc @jesstelford  something we didn't think about that might be worth while exploring with the team

**Comment by yurm04** [comment]
> I think we shouldn't be afraid of repeated content. Some things are worth saying more than once, and I get the feeling that the principles we've currently defined and placed under UX Guidance are one of those things.

💯 This feels like a good principle to establish early on once we come up with some strong opinions!

Thinking about this as a principle, i'm wondering what that might mean for our content architecture, specifically atomic/modular content that can be written once but repeated anywhere 🤔 This would also be an interesting jumping off point for tooling. For example, what if we had atomic documentation that can be repeated in UX + dev tabs. Then the same content could be served by an API for tooling clients like figma and vs code. 

Probably getting ahead of myself, but throwing ideas in here to explore!
