### ISSUE TITLE
Identify next patterns to document

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#8551]
## 1. Create a master list of potential next patterns

The list: [google sheet](https://docs.google.com/spreadsheets/d/1GWnBISQDwZnLDzjqeQMLVplr7SXjWrVTJ6UhDKd6i_Q/edit#gid=1194449845)

Don't worry about the definition of a "pattern" or priority at this point. We just want to list as many Admin patterns as possible based on feedback from a variety of sources.

- [ ] Audit https://web.docs.shopify.io/components/ for commonly used compositions that could be a pattern
- [ ] See if https://coverage.polaris.shopify.io/usage can give us insights on common compositions
- [ ] Gather commonly asked pattern questions in the [Admin UX Workplace](https://shopify.workplace.com/groups/1294395484626415) and [archived slack channel](https://shopify.slack.com/archives/C039ZAKQ5AA) for commonly discussed patterns
- [ ] Browse production Admin shops (e.g. https://abetterlookingshop.myshopify.com/admin/staff) for patterns or inconsistent patterns
- [x] Consolidate patterns from [the spreadsheet](https://docs.google.com/spreadsheets/d/1GWnBISQDwZnLDzjqeQMLVplr7SXjWrVTJ6UhDKd6i_Q/edit#gid=0)
- [x] Consolidate patterns from [this jam](https://www.figma.com/file/1rrKSV82R3o6k3fzKSjkF5/Pattern-candidates-jam?node-id=0%3A1&t=UZ4Z6lLpHhHbgO6G-1)
- [ ] Is there another way we can get feedback on this directly from our consumers?

## 2. Solidify a list of heuristics

[Jam on heuristics](https://www.figma.com/file/1rrKSV82R3o6k3fzKSjkF5/Pattern-candidates-jam?node-id=0%3A1&t=UZ4Z6lLpHhHbgO6G-1)

- [ ] What kind of precedent do we want to set in our pattern garden?
- [ ] What is NOT a good candidate?

## 3. Jam on selection

- [ ] Eliminate obvious options based on heuristics
- [ ] Collect feedback on what pattern to choose based on the heuristics
- [ ] Collaborate on choosing the patterns. We need 1 to work on immediately then approx 2 or 3 to draft during prototype.

**Comment by johanstromqvist** [comment]
> Is there another way we can get feedback on this directly from our consumers?

I can look into the opportunity to drop an ask or poll via workplace. Builders' own experiences and perspectives can probably add complementary qualitative input. Could ask questions like:
- What UX patterns or workflows do you perceive as least consistent in the admin?
- What missing UX patterns do you think has the most negative impact on the merchant experience?
- What sort of UI problems do you spend most time researching due to lack of documentation and guidance?

(I would prioritize this lower than heuristics and kicking off the first pattern for now)
