### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by fatbattk** [Shopify/polaris-react-archive#8782]
Not a fan of this default Props view (_folded/hidden_)
eg- https://polaris.shopify.com/components/selection-and-input/text-field#props
![image](https://user-images.githubusercontent.com/1505013/228386462-b85fd99a-1406-4e93-ac6b-1250ef0e672b.png)

Personally,
- it was too easy to glance over those links
- not obvious they were links.
- other components do not require toggling this.

**Recommendation:**
If anything the example and component's Props should be front and center of the documentation. If it does not parse well, it's better to default to showing it.

**Comment by martenbjork** [comment]
Hey! I agree, this is terrible. This is part of a bigger problem:

- Our types are complex. Our own `get-props` script can't understand them. Neither can third party scripts. That's why we just print this terrible props definition. We should fix the types at the source.
- The styling here is too subtle.

I want to address this by:

1. Fixing the styling and linking off to the source file. It's the best quick fix. Shipping it later this week:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/875708/228433203-53b35e87-b98f-421e-8e8b-c9706e57d988.png">

2. Fixing the props at the source. I will kick off a project for that next week.
