### ISSUE TITLE
Figma UI Kit not in sync with codebase

### ISSUE THREAD

**Issue by Milo-Nguyen-123** [Shopify/polaris-react-archive#9094]
## Issue summary

The Figma UI Kit is not up to date with the current state of the codebase

## Expected behavior

Update the Figma UI Kit so it is up to date with the codebase

**Comment by martenbjork** [comment]
Closing as the issue is not specific enough. Please provide more details.

**Comment by Milo-Nguyen-123** [comment]
Hi @martenbjork 
Could you please add the layout component to the Figma UI kit?
https://polaris.shopify.com/components/layout-and-structure/layout

**Comment by Milo-Nguyen-123** [comment]
Here it says that you could make the app settings layout using the VerticalStack, AlphaCard, HorizontalGrid, and Box components.
But they do not appear in the Figma UI kit neither
https://polaris.shopify.com/patterns/app-settings-layout

**Comment by martenbjork** [comment]
Thanks for providing more details. Some of the ones you mentioned probably won't be added to the Figma kit since Figma provides native alternatives, like AutoLayout. For AlphaCard and Box, I'll tag @heyjoethomas and see what the status is on those.

**Comment by Milo-Nguyen-123** [comment]
Thanks @martenbjork 
If possible, could you add the layout component? 
It would be easier to use the component directly instead of having to build it from scratch

**Comment by heyjoethomas** [comment]
> Here it says that you could make the app settings layout using the VerticalStack, AlphaCard, HorizontalGrid, and Box components. But they do not appear in the Figma UI kit neither https://polaris.shopify.com/patterns/app-settings-layout

Hi Milo, We did test a few things in an attempt to have them in Figma but never found a good solution. There is no great way to replicate them in Figma today. They would just be empty auto layout frames with loads of variants and properties. 

My recommendation is to just use auto layout and then collaborate with the developers. They will be able to choose the best layout component to achieve the design.  

`Box` would fall under the same category. Just use Figma natively since in code it is essentially an endlessly composable component. 

`AlphaCard` will be added to the community file next time we publish and it moves out of the Alpha phase. For Figma, there isn't a massive difference between it and the `Card` component. The changes were much more code focused. So using the `Card` component in Figma should still serve you well.
