### ISSUE TITLE
'Page' not showing like example

### ISSUE THREAD

**Issue by ghost** [Shopify/polaris-react-archive#91]
# Issue summary

When using the 'Page' component:

https://polaris.shopify.com/components/structure/page#examples

It is still styled in the old way within the dashboard (buttons at top right)?

## Expected behavior

As the example in the docs

## Actual behavior

Shows in the old style:
![old-style](https://user-images.githubusercontent.com/11619461/27083613-0bd1c3b2-5041-11e7-9190-4004fcf57565.png)

## Steps to Reproduce the Problem

1. Add in a 'Page' component

## Specifications

- Polaris version: 1.0.3
- Browser: Chrome 58
- Device: Macbook Pro
- Operating System: OSX 10.12.2

**Comment by lemonmade** [comment]
Hey @weareeight. We ended up having some trouble implementing the Polaris page header with embedded apps because of the scrolling behaviour. The intention is to follow up on the initial launch with a header that does match what you see elsewhere in the admin. As long as you continue to provide the relevant props to `Page` (or, directly through the EASDK), your application will continue to work when we make that switch.

**Comment by mariosant** [comment]
Hey @lemonmade, I am trying to use the embedded page as well. Any updates on this one?

**Comment by tmlayton** [comment]
Hey @mariosant, yes the embedded page component is being updated but will be more inline with the existing bar design.
