### ISSUE TITLE
[Patterns V1] Update patterns banner

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#9113]
@johanstromqvist [wrote](https://github.com/Shopify/polaris/issues/8949#issuecomment-1521014546):

The outstanding task is to update the banner. Here are my suggestions:
- [ ] Update the banner style to the standard doc site one (see ref below).
- [ ] Use headline `New` and background `--surface-information` to correspond to the badge in the nav
- [ ] Update the banner copy to `The pattern documentation is evolving. [Join the discussion] to make it better.`

**Comment by gwyneplaine** [comment]
updated for the `PatternsPage` in #9179 
@johanstromqvist  I'm assuming we also want this applied to the [`Date-picker`](https://polaris.shopify.com/components/selection-and-input/date-picker) and [`Page`](https://polaris.shopify.com/components/layout-and-structure/page) component page too. 

If yes, did you also want to make copy changes to those banners as well? They currently read 

![Image](https://github.com/Shopify/polaris/assets/12119389/9d2c8c27-6486-410b-8040-bc23a10b14dc)

Worthwhile noting that, leveraging the existing `status` mechanic in markdown for these pages will also make the `new` badge appear next to that item in the nav. Which may be confusing to users, since technically no "New" changes have been made to those component (or component documentation).

Here's a quick illustration of what that looks like: 

Before:
![Image](https://github.com/Shopify/polaris/assets/12119389/8e3ab6da-e82a-44c5-868f-4ce5fd46ef14)


After:
![Image](https://github.com/Shopify/polaris/assets/12119389/62943d50-c9b0-405c-b8ca-e4c1f506860e)

**Comment by johanstromqvist** [comment]
Awesome – great catch!

Agree, the "discovery banners" on related pages are more of a highlight or information character and shouldn't use `new`. I think we can use the `tip` banner found [here](https://polaris.shopify.com/components/layout-and-structure).

<img width="948" alt="image" src="https://github.com/Shopify/polaris/assets/38329124/1bc126ee-1c61-442b-bbbd-ecbbab84392b">

Copy:
`Check out the [new patterns section](https://polaris.shopify.com/patterns) to learn how merchants prefer to select dates in different scenarios!`
