### ISSUE TITLE
[PageAction] Separate destructive actions from primary action

### ISSUE THREAD

**Issue by martenbjork** [Shopify/polaris-react-archive#9170]
Destructive actions are currently grouped with the primary action. It makes it easy to accidentally perform a destructive action. It could lead to users being anxious about "pressing the wrong thing".

![Image](https://user-images.githubusercontent.com/875708/236833620-f46b4186-3959-425d-97e6-5ab25df2f3f1.png)

We should put the destructive actions to the left and the primary action to the right.

This behaviour was introduced in this PR: https://github.com/Shopify/polaris/pull/8115

**Comment by martenbjork** [comment]
Implemented in #9260

**Comment by johanstromqvist** [comment]
Nicely caught problem and sensible fix!

A bigger issue that we've come across is that common actions currently appear in various places on different details pages. It's important to consolidate these places so that merchants always intuitively know where to look.

- In the [details layout pattern](https://polaris.shopify.com/patterns/resource-details-layout) we recommend placing common actions in the page header, i.e. `archive` and `delete` in `secondaryActions` of `Page`
- `Save` action is handled by the `ContextualSaveBar`
- Here's an issue to [deprecate page action component](https://github.com/Shopify/polaris/issues/8198)

It hasn't been a priority to follow through on these updates yet, but keen to do it when we find some time.

**Comment by johanstromqvist** [comment]
Too important to get lost. @sarahill, do you think this might fit among our "common actions" initiatives?
