### ISSUE TITLE
Documentation: Text link color inconsistency

### ISSUE THREAD

**Issue by annaofthewoods** [Shopify/polaris-react-archive#95]
Awesome work on Polaris, the Sketch file is great.

I noticed an inconsistency in the 'Color Usage' section that may need clarification.

'Don't use indigo for text links', however within the documentation you are using indigo for text links. On the site #007ace seems to be the standard link color. Might also be helpful to specify proper text link color in that space.

![screen shot 2017-06-15 at 2 21 32 pm](https://user-images.githubusercontent.com/18662293/27205654-145d4266-5200-11e7-9144-bd3eb9a5f597.png)

**Comment by ry5n** [comment]
Thanks @annaofthewoods. TL;DR: if you’re building a Shopify app or channel, links should use blue, not indigo.

The detailed answer is that the polaris.shopify.com site shares its design language with the shopify.com site rather than with Shopify apps, like the Shopify admin or apps on the Shopify App Store. Currently polaris.shopify.com only documents the design language for those apps. We might make some changes to the styleguide site to avoid this confusion, but there are no plans to change the link color in the design system itself.
